// Autogenerated by generatorScripts/mcp/generate_mcp_tools.py. Do not edit.
const { z } = require('zod/v4');

const tool = {
    name: 'search_medication_dispense',
    resourceType: 'MedicationDispense',
    description: 'Search FHIR MedicationDispense resources using its supported search parameters. Comma-separate multiple values for the same parameter to OR them (e.g. \'active,inactive\'). Every parameter also accepts these FHIR search modifiers by appending \':modifier\' to the parameter name: :missing, :not, :contains, :exact, :above, :below, :text, :of-type (not every modifier is meaningful for every parameter -- see each parameter\'s own description for its expected value syntax).',
    inputSchema: z.object({
        _id: z.string().optional().describe('The logical resource id. (token) Format: \'system|code\', or bare \'code\' to match any system.'),
        _lastUpdated: z.string().optional().describe('When the resource was last updated. (date) Prefix the value with a comparator for a range match: eq, ne, gt, lt, ge, le, sa, eb, ap (e.g. \'ge2020-01-01\'). Omit the prefix for an exact match.'),
        _count: z.string().optional().describe('Number of results to return per page. A plain positive integer -- comparator prefixes are not supported. (number)'),
        _sort: z.string().optional().describe('Comma-separated fields to sort by; prefix a field with \'-\' for descending. Literal field names only -- \':exact\'/\':contains\' modifiers are not supported. (string)'),
        code: z.string().optional().describe('Returns dispenses of this medicine code (token) Format: \'system|code\', or bare \'code\' to match any system.'),
        identifier: z.string().optional().describe('Returns dispenses with this external identifier (token) Format: \'system|code\', or bare \'code\' to match any system.'),
        patient: z.string().optional().describe('The identity of a patient to list dispenses  for (reference: Patient) Format: \'ResourceType/id\', or bare \'id\' to match against any of this parameter\'s allowed target types.'),
        medication: z.string().optional().describe('Returns dispenses of this medicine resource (reference: Medication) Format: \'ResourceType/id\', or bare \'id\' to match against any of this parameter\'s allowed target types.'),
        status: z.string().optional().describe('Returns dispenses with a specified dispense status (token) Format: \'system|code\', or bare \'code\' to match any system.'),
        context: z.string().optional().describe('Returns dispenses with a specific context (episode or episode of care) (reference: EpisodeOfCare | Encounter) Format: \'ResourceType/id\', or bare \'id\' to match against any of this parameter\'s allowed target types.'),
        destination: z.string().optional().describe('Returns dispenses that should be sent to a specific destination (reference: Location) Format: \'ResourceType/id\', or bare \'id\' to match against any of this parameter\'s allowed target types.'),
        performer: z.string().optional().describe('Returns dispenses performed by a specific individual (reference: Practitioner | Organization | Device | Patient | PractitionerRole | RelatedPerson) Format: \'ResourceType/id\', or bare \'id\' to match against any of this parameter\'s allowed target types.'),
        prescription: z.string().optional().describe('The identity of a prescription to list dispenses from (reference: MedicationRequest) Format: \'ResourceType/id\', or bare \'id\' to match against any of this parameter\'s allowed target types.'),
        receiver: z.string().optional().describe('The identity of a receiver to list dispenses for (reference: Practitioner | Patient) Format: \'ResourceType/id\', or bare \'id\' to match against any of this parameter\'s allowed target types.'),
        responsibleparty: z.string().optional().describe('Returns dispenses with the specified responsible party (reference: Practitioner | PractitionerRole) Format: \'ResourceType/id\', or bare \'id\' to match against any of this parameter\'s allowed target types.'),
        subject: z.string().optional().describe('The identity of a patient for whom to list dispenses (reference: Group | Patient) Format: \'ResourceType/id\', or bare \'id\' to match against any of this parameter\'s allowed target types.'),
        type: z.string().optional().describe('Returns dispenses of a specific type (token) Format: \'system|code\', or bare \'code\' to match any system.'),
        whenhandedover: z.string().optional().describe('Returns dispenses handed over on this date (date) Prefix the value with a comparator for a range match: eq, ne, gt, lt, ge, le, sa, eb, ap (e.g. \'ge2020-01-01\'). Omit the prefix for an exact match.'),
        whenprepared: z.string().optional().describe('Returns dispenses prepared on this date (date) Prefix the value with a comparator for a range match: eq, ne, gt, lt, ge, le, sa, eb, ap (e.g. \'ge2020-01-01\'). Omit the prefix for an exact match.')
    }).passthrough()
};

module.exports = { tool };