/* eslint-disable no-unused-vars */
/* eslint-disable no-trailing-spaces */
// This file is auto-generated by generate_classes so do not edit manually

const Resource = require('../resources/resource');
const async = require('async');


/**
HealthcareService
    The details of a healthcare service available at a location.
    If the element is present, it must have either a @value, an @id, or extensions
*/
class HealthcareService extends Resource {
    /**
     * @param {id|undefined} [id],
     * @param {Meta|undefined} [meta],
     * @param {uri|undefined} [implicitRules],
     * @param {code|undefined} [language],
     * @param {Narrative|undefined} [text],
     * @param {ResourceContainer[]|undefined} [contained],
     * @param {Extension[]|undefined} [extension],
     * @param {Extension[]|undefined} [modifierExtension],
     * @param {Identifier[]|undefined} [identifier],
     * @param {Boolean|undefined} [active],
     * @param {Reference|undefined} [providedBy],
     * @param {CodeableConcept[]|undefined} [category],
     * @param {CodeableConcept[]|undefined} [type],
     * @param {CodeableConcept[]|undefined} [specialty],
     * @param {Reference[]|undefined} [location],
     * @param {String|undefined} [name],
     * @param {String|undefined} [comment],
     * @param {markdown|undefined} [extraDetails],
     * @param {Attachment|undefined} [photo],
     * @param {ContactPoint[]|undefined} [telecom],
     * @param {Reference[]|undefined} [coverageArea],
     * @param {CodeableConcept[]|undefined} [serviceProvisionCode],
     * @param {HealthcareServiceEligibility[]|undefined} [eligibility],
     * @param {CodeableConcept[]|undefined} [program],
     * @param {CodeableConcept[]|undefined} [characteristic],
     * @param {CodeableConcept[]|undefined} [communication],
     * @param {CodeableConcept[]|undefined} [referralMethod],
     * @param {Boolean|undefined} [appointmentRequired],
     * @param {HealthcareServiceAvailableTime[]|undefined} [availableTime],
     * @param {HealthcareServiceNotAvailable[]|undefined} [notAvailable],
     * @param {String|undefined} [availabilityExceptions],
     * @param {Reference[]|undefined} [endpoint],
     * @param {Object|undefined} [_access]
     * @param {string|undefined} [_sourceAssigningAuthority]
     * @param {string|undefined} [_uuid]
     * @param {string|undefined} [_sourceId]
    */
    constructor(
        {
            id,
            meta,
            implicitRules,
            language,
            text,
            contained,
            extension,
            modifierExtension,
            identifier,
            active,
            providedBy,
            category,
            type,
            specialty,
            location,
            name,
            comment,
            extraDetails,
            photo,
            telecom,
            coverageArea,
            serviceProvisionCode,
            eligibility,
            program,
            characteristic,
            communication,
            referralMethod,
            appointmentRequired,
            availableTime,
            notAvailable,
            availabilityExceptions,
            endpoint,
            _access,
            _sourceAssigningAuthority,
            _uuid,
            _sourceId
        }
    ) {
        super({});

        // ---- Define getters and setters as enumerable ---

        /**
         * @description The logical id of the resource, as used in the URL for the resource. Once
    assigned, this value never changes.
         * @property {id|undefined}
        */
        Object.defineProperty(this, 'id', {
            // https://www.w3schools.com/js/js_object_es5.asp
            enumerable: true,
            configurable: true,
            get: () => this.__data.id,
            set: valueProvided => {
                if (valueProvided === undefined || valueProvided === null || (Array.isArray(valueProvided) && valueProvided.length === 0)) {
                    this.__data.id = undefined;
                    return;
                }
                this.__data.id = valueProvided;
            }
        });

        /**
         * @description The metadata about the resource. This is content that is maintained by the
    infrastructure. Changes to the content might not always be associated with
    version changes to the resource.
         * @property {Meta|undefined}
        */
        Object.defineProperty(this, 'meta', {
            // https://www.w3schools.com/js/js_object_es5.asp
            enumerable: true,
            configurable: true,
            get: () => this.__data.meta,
            set: valueProvided => {
                if (valueProvided === undefined || valueProvided === null || (Array.isArray(valueProvided) && valueProvided.length === 0)) {
                    this.__data.meta = undefined;
                    return;
                }
                const Meta = require('../complex_types/meta.js');
                const {FhirResourceCreator} = require('../../../fhirResourceCreator');
                this.__data.meta = FhirResourceCreator.create(valueProvided, Meta);
            }
        });

        /**
         * @description A reference to a set of rules that were followed when the resource was
    constructed, and which must be understood when processing the content. Often,
    this is a reference to an implementation guide that defines the special rules
    along with other profiles etc.
         * @property {uri|undefined}
        */
        Object.defineProperty(this, 'implicitRules', {
            // https://www.w3schools.com/js/js_object_es5.asp
            enumerable: true,
            configurable: true,
            get: () => this.__data.implicitRules,
            set: valueProvided => {
                if (valueProvided === undefined || valueProvided === null || (Array.isArray(valueProvided) && valueProvided.length === 0)) {
                    this.__data.implicitRules = undefined;
                    return;
                }
                this.__data.implicitRules = valueProvided;
            }
        });

        /**
         * @description The base language in which the resource is written.
         * @property {code|undefined}
        */
        Object.defineProperty(this, 'language', {
            // https://www.w3schools.com/js/js_object_es5.asp
            enumerable: true,
            configurable: true,
            get: () => this.__data.language,
            set: valueProvided => {
                if (valueProvided === undefined || valueProvided === null || (Array.isArray(valueProvided) && valueProvided.length === 0)) {
                    this.__data.language = undefined;
                    return;
                }
                this.__data.language = valueProvided;
            }
        });

        /**
         * @description A human-readable narrative that contains a summary of the resource and can be
    used to represent the content of the resource to a human. The narrative need
    not encode all the structured data, but is required to contain sufficient
    detail to make it "clinically safe" for a human to just read the narrative.
    Resource definitions may define what content should be represented in the
    narrative to ensure clinical safety.
         * @property {Narrative|undefined}
        */
        Object.defineProperty(this, 'text', {
            // https://www.w3schools.com/js/js_object_es5.asp
            enumerable: true,
            configurable: true,
            get: () => this.__data.text,
            set: valueProvided => {
                if (valueProvided === undefined || valueProvided === null || (Array.isArray(valueProvided) && valueProvided.length === 0)) {
                    this.__data.text = undefined;
                    return;
                }
                const Narrative = require('../complex_types/narrative.js');
                const {FhirResourceCreator} = require('../../../fhirResourceCreator');
                this.__data.text = FhirResourceCreator.create(valueProvided, Narrative);
            }
        });

        /**
         * @description These resources do not have an independent existence apart from the resource
    that contains them - they cannot be identified independently, and nor can they
    have their own independent transaction scope.
         * @property {ResourceContainer[]|undefined}
        */
        Object.defineProperty(this, 'contained', {
            // https://www.w3schools.com/js/js_object_es5.asp
            enumerable: true,
            configurable: true,
            get: () => this.__data.contained,
            set: valueProvided => {
                if (valueProvided === undefined || valueProvided === null || (Array.isArray(valueProvided) && valueProvided.length === 0)) {
                    this.__data.contained = undefined;
                    return;
                }
                const ResourceContainer = require('../simple_types/resourceContainer.js');
                const {FhirResourceCreator} = require('../../../fhirResourceCreator');
                this.__data.contained = FhirResourceCreator.createArray(valueProvided);
            }
        });

        /**
         * @description May be used to represent additional information that is not part of the basic
    definition of the resource. To make the use of extensions safe and manageable,
    there is a strict set of governance  applied to the definition and use of
    extensions. Though any implementer can define an extension, there is a set of
    requirements that SHALL be met as part of the definition of the extension.
         * @property {Extension[]|undefined}
        */
        Object.defineProperty(this, 'extension', {
            // https://www.w3schools.com/js/js_object_es5.asp
            enumerable: true,
            configurable: true,
            get: () => this.__data.extension,
            set: valueProvided => {
                if (valueProvided === undefined || valueProvided === null || (Array.isArray(valueProvided) && valueProvided.length === 0)) {
                    this.__data.extension = undefined;
                    return;
                }
                const Extension = require('../complex_types/extension.js');
                const {FhirResourceCreator} = require('../../../fhirResourceCreator');
                this.__data.extension = FhirResourceCreator.createArray(valueProvided, Extension);
            }
        });

        /**
         * @description May be used to represent additional information that is not part of the basic
    definition of the resource and that modifies the understanding of the element
    that contains it and/or the understanding of the containing element's
    descendants. Usually modifier elements provide negation or qualification. To
    make the use of extensions safe and manageable, there is a strict set of
    governance applied to the definition and use of extensions. Though any
    implementer is allowed to define an extension, there is a set of requirements
    that SHALL be met as part of the definition of the extension. Applications
    processing a resource are required to check for modifier extensions.
    
    Modifier extensions SHALL NOT change the meaning of any elements on Resource
    or DomainResource (including cannot change the meaning of modifierExtension
    itself).
         * @property {Extension[]|undefined}
        */
        Object.defineProperty(this, 'modifierExtension', {
            // https://www.w3schools.com/js/js_object_es5.asp
            enumerable: true,
            configurable: true,
            get: () => this.__data.modifierExtension,
            set: valueProvided => {
                if (valueProvided === undefined || valueProvided === null || (Array.isArray(valueProvided) && valueProvided.length === 0)) {
                    this.__data.modifierExtension = undefined;
                    return;
                }
                const Extension = require('../complex_types/extension.js');
                const {FhirResourceCreator} = require('../../../fhirResourceCreator');
                this.__data.modifierExtension = FhirResourceCreator.createArray(valueProvided, Extension);
            }
        });

        /**
         * @description External identifiers for this item.
         * @property {Identifier[]|undefined}
        */
        Object.defineProperty(this, 'identifier', {
            // https://www.w3schools.com/js/js_object_es5.asp
            enumerable: true,
            configurable: true,
            get: () => this.__data.identifier,
            set: valueProvided => {
                if (valueProvided === undefined || valueProvided === null || (Array.isArray(valueProvided) && valueProvided.length === 0)) {
                    this.__data.identifier = undefined;
                    return;
                }
                const Identifier = require('../complex_types/identifier.js');
                const {FhirResourceCreator} = require('../../../fhirResourceCreator');
                this.__data.identifier = FhirResourceCreator.createArray(valueProvided, Identifier);
            }
        });

        /**
         * @description This flag is used to mark the record to not be used. This is not used when a
    center is closed for maintenance, or for holidays, the notAvailable period is
    to be used for this.
         * @property {Boolean|undefined}
        */
        Object.defineProperty(this, 'active', {
            // https://www.w3schools.com/js/js_object_es5.asp
            enumerable: true,
            configurable: true,
            get: () => this.__data.active,
            set: valueProvided => {
                if (valueProvided === undefined || valueProvided === null || (Array.isArray(valueProvided) && valueProvided.length === 0)) {
                    this.__data.active = undefined;
                    return;
                }
                this.__data.active = valueProvided;
            }
        });

        /**
         * @description The organization that provides this healthcare service.
         * @property {Reference|undefined}
        */
        Object.defineProperty(this, 'providedBy', {
            // https://www.w3schools.com/js/js_object_es5.asp
            enumerable: true,
            configurable: true,
            get: () => this.__data.providedBy,
            set: valueProvided => {
                if (valueProvided === undefined || valueProvided === null || (Array.isArray(valueProvided) && valueProvided.length === 0)) {
                    this.__data.providedBy = undefined;
                    return;
                }
                const Reference = require('../complex_types/reference.js');
                const {FhirResourceCreator} = require('../../../fhirResourceCreator');
                this.__data.providedBy = FhirResourceCreator.create(valueProvided, Reference);
            }
        });

        /**
         * @description Identifies the broad category of service being performed or delivered.
         * @property {CodeableConcept[]|undefined}
        */
        Object.defineProperty(this, 'category', {
            // https://www.w3schools.com/js/js_object_es5.asp
            enumerable: true,
            configurable: true,
            get: () => this.__data.category,
            set: valueProvided => {
                if (valueProvided === undefined || valueProvided === null || (Array.isArray(valueProvided) && valueProvided.length === 0)) {
                    this.__data.category = undefined;
                    return;
                }
                const CodeableConcept = require('../complex_types/codeableConcept.js');
                const {FhirResourceCreator} = require('../../../fhirResourceCreator');
                this.__data.category = FhirResourceCreator.createArray(valueProvided, CodeableConcept);
            }
        });

        /**
         * @description The specific type of service that may be delivered or performed.
         * @property {CodeableConcept[]|undefined}
        */
        Object.defineProperty(this, 'type', {
            // https://www.w3schools.com/js/js_object_es5.asp
            enumerable: true,
            configurable: true,
            get: () => this.__data.type,
            set: valueProvided => {
                if (valueProvided === undefined || valueProvided === null || (Array.isArray(valueProvided) && valueProvided.length === 0)) {
                    this.__data.type = undefined;
                    return;
                }
                const CodeableConcept = require('../complex_types/codeableConcept.js');
                const {FhirResourceCreator} = require('../../../fhirResourceCreator');
                this.__data.type = FhirResourceCreator.createArray(valueProvided, CodeableConcept);
            }
        });

        /**
         * @description Collection of specialties handled by the service site. This is more of a
    medical term.
         * @property {CodeableConcept[]|undefined}
        */
        Object.defineProperty(this, 'specialty', {
            // https://www.w3schools.com/js/js_object_es5.asp
            enumerable: true,
            configurable: true,
            get: () => this.__data.specialty,
            set: valueProvided => {
                if (valueProvided === undefined || valueProvided === null || (Array.isArray(valueProvided) && valueProvided.length === 0)) {
                    this.__data.specialty = undefined;
                    return;
                }
                const CodeableConcept = require('../complex_types/codeableConcept.js');
                const {FhirResourceCreator} = require('../../../fhirResourceCreator');
                this.__data.specialty = FhirResourceCreator.createArray(valueProvided, CodeableConcept);
            }
        });

        /**
         * @description The location(s) where this healthcare service may be provided.
         * @property {Reference[]|undefined}
        */
        Object.defineProperty(this, 'location', {
            // https://www.w3schools.com/js/js_object_es5.asp
            enumerable: true,
            configurable: true,
            get: () => this.__data.location,
            set: valueProvided => {
                if (valueProvided === undefined || valueProvided === null || (Array.isArray(valueProvided) && valueProvided.length === 0)) {
                    this.__data.location = undefined;
                    return;
                }
                const Reference = require('../complex_types/reference.js');
                const {FhirResourceCreator} = require('../../../fhirResourceCreator');
                this.__data.location = FhirResourceCreator.createArray(valueProvided, Reference);
            }
        });

        /**
         * @description Further description of the service as it would be presented to a consumer
    while searching.
         * @property {String|undefined}
        */
        Object.defineProperty(this, 'name', {
            // https://www.w3schools.com/js/js_object_es5.asp
            enumerable: true,
            configurable: true,
            get: () => this.__data.name,
            set: valueProvided => {
                if (valueProvided === undefined || valueProvided === null || (Array.isArray(valueProvided) && valueProvided.length === 0)) {
                    this.__data.name = undefined;
                    return;
                }
                this.__data.name = valueProvided;
            }
        });

        /**
         * @description Any additional description of the service and/or any specific issues not
    covered by the other attributes, which can be displayed as further detail
    under the serviceName.
         * @property {String|undefined}
        */
        Object.defineProperty(this, 'comment', {
            // https://www.w3schools.com/js/js_object_es5.asp
            enumerable: true,
            configurable: true,
            get: () => this.__data.comment,
            set: valueProvided => {
                if (valueProvided === undefined || valueProvided === null || (Array.isArray(valueProvided) && valueProvided.length === 0)) {
                    this.__data.comment = undefined;
                    return;
                }
                this.__data.comment = valueProvided;
            }
        });

        /**
         * @description Extra details about the service that can't be placed in the other fields.
         * @property {markdown|undefined}
        */
        Object.defineProperty(this, 'extraDetails', {
            // https://www.w3schools.com/js/js_object_es5.asp
            enumerable: true,
            configurable: true,
            get: () => this.__data.extraDetails,
            set: valueProvided => {
                if (valueProvided === undefined || valueProvided === null || (Array.isArray(valueProvided) && valueProvided.length === 0)) {
                    this.__data.extraDetails = undefined;
                    return;
                }
                this.__data.extraDetails = valueProvided;
            }
        });

        /**
         * @description If there is a photo/symbol associated with this HealthcareService, it may be
    included here to facilitate quick identification of the service in a list.
         * @property {Attachment|undefined}
        */
        Object.defineProperty(this, 'photo', {
            // https://www.w3schools.com/js/js_object_es5.asp
            enumerable: true,
            configurable: true,
            get: () => this.__data.photo,
            set: valueProvided => {
                if (valueProvided === undefined || valueProvided === null || (Array.isArray(valueProvided) && valueProvided.length === 0)) {
                    this.__data.photo = undefined;
                    return;
                }
                const Attachment = require('../complex_types/attachment.js');
                const {FhirResourceCreator} = require('../../../fhirResourceCreator');
                this.__data.photo = FhirResourceCreator.create(valueProvided, Attachment);
            }
        });

        /**
         * @description List of contacts related to this specific healthcare service.
         * @property {ContactPoint[]|undefined}
        */
        Object.defineProperty(this, 'telecom', {
            // https://www.w3schools.com/js/js_object_es5.asp
            enumerable: true,
            configurable: true,
            get: () => this.__data.telecom,
            set: valueProvided => {
                if (valueProvided === undefined || valueProvided === null || (Array.isArray(valueProvided) && valueProvided.length === 0)) {
                    this.__data.telecom = undefined;
                    return;
                }
                const ContactPoint = require('../complex_types/contactPoint.js');
                const {FhirResourceCreator} = require('../../../fhirResourceCreator');
                this.__data.telecom = FhirResourceCreator.createArray(valueProvided, ContactPoint);
            }
        });

        /**
         * @description The location(s) that this service is available to (not where the service is
    provided).
         * @property {Reference[]|undefined}
        */
        Object.defineProperty(this, 'coverageArea', {
            // https://www.w3schools.com/js/js_object_es5.asp
            enumerable: true,
            configurable: true,
            get: () => this.__data.coverageArea,
            set: valueProvided => {
                if (valueProvided === undefined || valueProvided === null || (Array.isArray(valueProvided) && valueProvided.length === 0)) {
                    this.__data.coverageArea = undefined;
                    return;
                }
                const Reference = require('../complex_types/reference.js');
                const {FhirResourceCreator} = require('../../../fhirResourceCreator');
                this.__data.coverageArea = FhirResourceCreator.createArray(valueProvided, Reference);
            }
        });

        /**
         * @description The code(s) that detail the conditions under which the healthcare service is
    available/offered.
         * @property {CodeableConcept[]|undefined}
        */
        Object.defineProperty(this, 'serviceProvisionCode', {
            // https://www.w3schools.com/js/js_object_es5.asp
            enumerable: true,
            configurable: true,
            get: () => this.__data.serviceProvisionCode,
            set: valueProvided => {
                if (valueProvided === undefined || valueProvided === null || (Array.isArray(valueProvided) && valueProvided.length === 0)) {
                    this.__data.serviceProvisionCode = undefined;
                    return;
                }
                const CodeableConcept = require('../complex_types/codeableConcept.js');
                const {FhirResourceCreator} = require('../../../fhirResourceCreator');
                this.__data.serviceProvisionCode = FhirResourceCreator.createArray(valueProvided, CodeableConcept);
            }
        });

        /**
         * @description Does this service have specific eligibility requirements that need to be met
    in order to use the service?
         * @property {HealthcareServiceEligibility[]|undefined}
        */
        Object.defineProperty(this, 'eligibility', {
            // https://www.w3schools.com/js/js_object_es5.asp
            enumerable: true,
            configurable: true,
            get: () => this.__data.eligibility,
            set: valueProvided => {
                if (valueProvided === undefined || valueProvided === null || (Array.isArray(valueProvided) && valueProvided.length === 0)) {
                    this.__data.eligibility = undefined;
                    return;
                }
                const HealthcareServiceEligibility = require('../backbone_elements/healthcareServiceEligibility.js');
                const {FhirResourceCreator} = require('../../../fhirResourceCreator');
                this.__data.eligibility = FhirResourceCreator.createArray(valueProvided, HealthcareServiceEligibility);
            }
        });

        /**
         * @description Programs that this service is applicable to.
         * @property {CodeableConcept[]|undefined}
        */
        Object.defineProperty(this, 'program', {
            // https://www.w3schools.com/js/js_object_es5.asp
            enumerable: true,
            configurable: true,
            get: () => this.__data.program,
            set: valueProvided => {
                if (valueProvided === undefined || valueProvided === null || (Array.isArray(valueProvided) && valueProvided.length === 0)) {
                    this.__data.program = undefined;
                    return;
                }
                const CodeableConcept = require('../complex_types/codeableConcept.js');
                const {FhirResourceCreator} = require('../../../fhirResourceCreator');
                this.__data.program = FhirResourceCreator.createArray(valueProvided, CodeableConcept);
            }
        });

        /**
         * @description Collection of characteristics (attributes).
         * @property {CodeableConcept[]|undefined}
        */
        Object.defineProperty(this, 'characteristic', {
            // https://www.w3schools.com/js/js_object_es5.asp
            enumerable: true,
            configurable: true,
            get: () => this.__data.characteristic,
            set: valueProvided => {
                if (valueProvided === undefined || valueProvided === null || (Array.isArray(valueProvided) && valueProvided.length === 0)) {
                    this.__data.characteristic = undefined;
                    return;
                }
                const CodeableConcept = require('../complex_types/codeableConcept.js');
                const {FhirResourceCreator} = require('../../../fhirResourceCreator');
                this.__data.characteristic = FhirResourceCreator.createArray(valueProvided, CodeableConcept);
            }
        });

        /**
         * @description Some services are specifically made available in multiple languages, this
    property permits a directory to declare the languages this is offered in.
    Typically this is only provided where a service operates in communities with
    mixed languages used.
         * @property {CodeableConcept[]|undefined}
        */
        Object.defineProperty(this, 'communication', {
            // https://www.w3schools.com/js/js_object_es5.asp
            enumerable: true,
            configurable: true,
            get: () => this.__data.communication,
            set: valueProvided => {
                if (valueProvided === undefined || valueProvided === null || (Array.isArray(valueProvided) && valueProvided.length === 0)) {
                    this.__data.communication = undefined;
                    return;
                }
                const CodeableConcept = require('../complex_types/codeableConcept.js');
                const {FhirResourceCreator} = require('../../../fhirResourceCreator');
                this.__data.communication = FhirResourceCreator.createArray(valueProvided, CodeableConcept);
            }
        });

        /**
         * @description Ways that the service accepts referrals, if this is not provided then it is
    implied that no referral is required.
         * @property {CodeableConcept[]|undefined}
        */
        Object.defineProperty(this, 'referralMethod', {
            // https://www.w3schools.com/js/js_object_es5.asp
            enumerable: true,
            configurable: true,
            get: () => this.__data.referralMethod,
            set: valueProvided => {
                if (valueProvided === undefined || valueProvided === null || (Array.isArray(valueProvided) && valueProvided.length === 0)) {
                    this.__data.referralMethod = undefined;
                    return;
                }
                const CodeableConcept = require('../complex_types/codeableConcept.js');
                const {FhirResourceCreator} = require('../../../fhirResourceCreator');
                this.__data.referralMethod = FhirResourceCreator.createArray(valueProvided, CodeableConcept);
            }
        });

        /**
         * @description Indicates whether or not a prospective consumer will require an appointment
    for a particular service at a site to be provided by the Organization.
    Indicates if an appointment is required for access to this service.
         * @property {Boolean|undefined}
        */
        Object.defineProperty(this, 'appointmentRequired', {
            // https://www.w3schools.com/js/js_object_es5.asp
            enumerable: true,
            configurable: true,
            get: () => this.__data.appointmentRequired,
            set: valueProvided => {
                if (valueProvided === undefined || valueProvided === null || (Array.isArray(valueProvided) && valueProvided.length === 0)) {
                    this.__data.appointmentRequired = undefined;
                    return;
                }
                this.__data.appointmentRequired = valueProvided;
            }
        });

        /**
         * @description A collection of times that the Service Site is available.
         * @property {HealthcareServiceAvailableTime[]|undefined}
        */
        Object.defineProperty(this, 'availableTime', {
            // https://www.w3schools.com/js/js_object_es5.asp
            enumerable: true,
            configurable: true,
            get: () => this.__data.availableTime,
            set: valueProvided => {
                if (valueProvided === undefined || valueProvided === null || (Array.isArray(valueProvided) && valueProvided.length === 0)) {
                    this.__data.availableTime = undefined;
                    return;
                }
                const HealthcareServiceAvailableTime = require('../backbone_elements/healthcareServiceAvailableTime.js');
                const {FhirResourceCreator} = require('../../../fhirResourceCreator');
                this.__data.availableTime = FhirResourceCreator.createArray(valueProvided, HealthcareServiceAvailableTime);
            }
        });

        /**
         * @description The HealthcareService is not available during this period of time due to the
    provided reason.
         * @property {HealthcareServiceNotAvailable[]|undefined}
        */
        Object.defineProperty(this, 'notAvailable', {
            // https://www.w3schools.com/js/js_object_es5.asp
            enumerable: true,
            configurable: true,
            get: () => this.__data.notAvailable,
            set: valueProvided => {
                if (valueProvided === undefined || valueProvided === null || (Array.isArray(valueProvided) && valueProvided.length === 0)) {
                    this.__data.notAvailable = undefined;
                    return;
                }
                const HealthcareServiceNotAvailable = require('../backbone_elements/healthcareServiceNotAvailable.js');
                const {FhirResourceCreator} = require('../../../fhirResourceCreator');
                this.__data.notAvailable = FhirResourceCreator.createArray(valueProvided, HealthcareServiceNotAvailable);
            }
        });

        /**
         * @description A description of site availability exceptions, e.g. public holiday
    availability. Succinctly describing all possible exceptions to normal site
    availability as details in the available Times and not available Times.
         * @property {String|undefined}
        */
        Object.defineProperty(this, 'availabilityExceptions', {
            // https://www.w3schools.com/js/js_object_es5.asp
            enumerable: true,
            configurable: true,
            get: () => this.__data.availabilityExceptions,
            set: valueProvided => {
                if (valueProvided === undefined || valueProvided === null || (Array.isArray(valueProvided) && valueProvided.length === 0)) {
                    this.__data.availabilityExceptions = undefined;
                    return;
                }
                this.__data.availabilityExceptions = valueProvided;
            }
        });

        /**
         * @description Technical endpoints providing access to services operated for the specific
    healthcare services defined at this resource.
         * @property {Reference[]|undefined}
        */
        Object.defineProperty(this, 'endpoint', {
            // https://www.w3schools.com/js/js_object_es5.asp
            enumerable: true,
            configurable: true,
            get: () => this.__data.endpoint,
            set: valueProvided => {
                if (valueProvided === undefined || valueProvided === null || (Array.isArray(valueProvided) && valueProvided.length === 0)) {
                    this.__data.endpoint = undefined;
                    return;
                }
                const Reference = require('../complex_types/reference.js');
                const {FhirResourceCreator} = require('../../../fhirResourceCreator');
                this.__data.endpoint = FhirResourceCreator.createArray(valueProvided, Reference);
            }
        });


        /**
         * @description _access
         * @property {Object|undefined}
         */
        Object.defineProperty(this, '_access', {
            // https://www.w3schools.com/js/js_object_es5.asp
            enumerable: true,
            configurable: true,
            get: () => this.__data._access,
            set: valueProvided => {
                this.__data._access = valueProvided;
            }
        });
        /**
         * @description _sourceAssigningAuthority
         * @property {string|undefined}
         */
        Object.defineProperty(this, '_sourceAssigningAuthority', {
            // https://www.w3schools.com/js/js_object_es5.asp
            enumerable: true,
            configurable: true,
            get: () => this.__data._sourceAssigningAuthority,
            set: valueProvided => {
                this.__data._sourceAssigningAuthority = valueProvided;
            }
        });
        /**
         * @description _uuid
         * @property {string|undefined}
         */
        Object.defineProperty(this, '_uuid', {
            // https://www.w3schools.com/js/js_object_es5.asp
            enumerable: true,
            configurable: true,
            get: () => this.__data._uuid,
            set: valueProvided => {
                this.__data._uuid = valueProvided;
            }
        });
        /**
         * @description _sourceId
         * @property {string|undefined}
         */
        Object.defineProperty(this, '_sourceId', {
            // https://www.w3schools.com/js/js_object_es5.asp
            enumerable: true,
            configurable: true,
            get: () => this.__data._sourceId,
            set: valueProvided => {
                this.__data._sourceId = valueProvided;
            }
        });


        // --- Now copy properties from passed in object ----
        Object.assign(this, {
            id,
            meta,
            implicitRules,
            language,
            text,
            contained,
            extension,
            modifierExtension,
            identifier,
            active,
            providedBy,
            category,
            type,
            specialty,
            location,
            name,
            comment,
            extraDetails,
            photo,
            telecom,
            coverageArea,
            serviceProvisionCode,
            eligibility,
            program,
            characteristic,
            communication,
            referralMethod,
            appointmentRequired,
            availableTime,
            notAvailable,
            availabilityExceptions,
            endpoint,
            _access,
            _sourceAssigningAuthority,
            _uuid,
            _sourceId
        });

        /**
         * @description Define a default non-writable resourceType property
         * @property {string|undefined}
         */
        Object.defineProperty(this, 'resourceType', {
            value: 'HealthcareService',
            enumerable: true,
            writable: false,
            configurable: true
        });
    }

    /**
     * @description Define a default non-writable resourceType property
     * @property {string|undefined}
     */
    static get resourceType() {
        return 'HealthcareService';
    }

    /**
     * @description Creates a blank new resource
     * @param {id|undefined} [id],
     * @param {Meta|undefined} [meta],
     * @param {uri|undefined} [implicitRules],
     * @param {code|undefined} [language],
     * @param {Narrative|undefined} [text],
     * @param {ResourceContainer[]|undefined} [contained],
     * @param {Extension[]|undefined} [extension],
     * @param {Extension[]|undefined} [modifierExtension],
     * @param {Identifier[]|undefined} [identifier],
     * @param {Boolean|undefined} [active],
     * @param {Reference|undefined} [providedBy],
     * @param {CodeableConcept[]|undefined} [category],
     * @param {CodeableConcept[]|undefined} [type],
     * @param {CodeableConcept[]|undefined} [specialty],
     * @param {Reference[]|undefined} [location],
     * @param {String|undefined} [name],
     * @param {String|undefined} [comment],
     * @param {markdown|undefined} [extraDetails],
     * @param {Attachment|undefined} [photo],
     * @param {ContactPoint[]|undefined} [telecom],
     * @param {Reference[]|undefined} [coverageArea],
     * @param {CodeableConcept[]|undefined} [serviceProvisionCode],
     * @param {HealthcareServiceEligibility[]|undefined} [eligibility],
     * @param {CodeableConcept[]|undefined} [program],
     * @param {CodeableConcept[]|undefined} [characteristic],
     * @param {CodeableConcept[]|undefined} [communication],
     * @param {CodeableConcept[]|undefined} [referralMethod],
     * @param {Boolean|undefined} [appointmentRequired],
     * @param {HealthcareServiceAvailableTime[]|undefined} [availableTime],
     * @param {HealthcareServiceNotAvailable[]|undefined} [notAvailable],
     * @param {String|undefined} [availabilityExceptions],
     * @param {Reference[]|undefined} [endpoint],
     * @param {Object|undefined} [_access]
     * @param {string|undefined} [_sourceAssigningAuthority]
     * @param {string|undefined} [_uuid]
     * @param {string|undefined} [_sourceId]
     * @returns {HealthcareService}
    */
    create(
            {
            id,
            meta,
            implicitRules,
            language,
            text,
            contained,
            extension,
            modifierExtension,
            identifier,
            active,
            providedBy,
            category,
            type,
            specialty,
            location,
            name,
            comment,
            extraDetails,
            photo,
            telecom,
            coverageArea,
            serviceProvisionCode,
            eligibility,
            program,
            characteristic,
            communication,
            referralMethod,
            appointmentRequired,
            availableTime,
            notAvailable,
            availabilityExceptions,
            endpoint,
            _access,
            _sourceAssigningAuthority,
            _uuid,
            _sourceId
        }
    ) {
        return new HealthcareService({
            id,
            meta,
            implicitRules,
            language,
            text,
            contained,
            extension,
            modifierExtension,
            identifier,
            active,
            providedBy,
            category,
            type,
            specialty,
            location,
            name,
            comment,
            extraDetails,
            photo,
            telecom,
            coverageArea,
            serviceProvisionCode,
            eligibility,
            program,
            characteristic,
            communication,
            referralMethod,
            appointmentRequired,
            availableTime,
            notAvailable,
            availabilityExceptions,
            endpoint,
            _access,
            _sourceAssigningAuthority,
            _uuid,
            _sourceId
        });
    }

    /**
     * @description creates a copy of this resource
     * @returns {HealthcareService}
    */
    clone() {
        return new HealthcareService(this.toJSONInternal());
    }


    /**
     * Returns JSON representation of entity
     * @return {Object}
     */
    toJSON() {
        const {removeNull} = require('../../../../utils/nullRemover');

        return removeNull({
            resourceType: this.resourceType,
            id: this.id,
            meta: this.meta && this.meta.toJSON(),
            implicitRules: this.implicitRules,
            language: this.language,
            text: this.text && this.text.toJSON(),
            contained: this.contained && this.contained.map(v => v.toJSON()),
            extension: this.extension && this.extension.map(v => v.toJSON()),
            modifierExtension: this.modifierExtension && this.modifierExtension.map(v => v.toJSON()),
            identifier: this.identifier && this.identifier.map(v => v.toJSON()),
            active: this.active,
            providedBy: this.providedBy && this.providedBy.toJSON(),
            category: this.category && this.category.map(v => v.toJSON()),
            type: this.type && this.type.map(v => v.toJSON()),
            specialty: this.specialty && this.specialty.map(v => v.toJSON()),
            location: this.location && this.location.map(v => v.toJSON()),
            name: this.name,
            comment: this.comment,
            extraDetails: this.extraDetails,
            photo: this.photo && this.photo.toJSON(),
            telecom: this.telecom && this.telecom.map(v => v.toJSON()),
            coverageArea: this.coverageArea && this.coverageArea.map(v => v.toJSON()),
            serviceProvisionCode: this.serviceProvisionCode && this.serviceProvisionCode.map(v => v.toJSON()),
            eligibility: this.eligibility && this.eligibility.map(v => v.toJSON()),
            program: this.program && this.program.map(v => v.toJSON()),
            characteristic: this.characteristic && this.characteristic.map(v => v.toJSON()),
            communication: this.communication && this.communication.map(v => v.toJSON()),
            referralMethod: this.referralMethod && this.referralMethod.map(v => v.toJSON()),
            appointmentRequired: this.appointmentRequired,
            availableTime: this.availableTime && this.availableTime.map(v => v.toJSON()),
            notAvailable: this.notAvailable && this.notAvailable.map(v => v.toJSON()),
            availabilityExceptions: this.availabilityExceptions,
            endpoint: this.endpoint && this.endpoint.map(v => v.toJSON())
        });
    }

    /**
     * Returns JSON representation of entity
     * @param {function(Reference): Promise<Reference>} fnUpdateReferenceAsync
     * @return {void}
     */
    async updateReferencesAsync({fnUpdateReferenceAsync}) {
            if (this.meta) { await this.meta.updateReferencesAsync({fnUpdateReferenceAsync}); }
            if (this.text) { await this.text.updateReferencesAsync({fnUpdateReferenceAsync}); }
            if (this.contained) { await async.each(this.contained, async v => await v.updateReferencesAsync({fnUpdateReferenceAsync})); }
            if (this.extension) { await async.each(this.extension, async v => await v.updateReferencesAsync({fnUpdateReferenceAsync})); }
            if (this.modifierExtension) { await async.each(this.modifierExtension, async v => await v.updateReferencesAsync({fnUpdateReferenceAsync})); }
            if (this.identifier) { await async.each(this.identifier, async v => await v.updateReferencesAsync({fnUpdateReferenceAsync})); }
            if (this.providedBy) { await this.providedBy.updateReferencesAsync({fnUpdateReferenceAsync}); }
            if (this.category) { await async.each(this.category, async v => await v.updateReferencesAsync({fnUpdateReferenceAsync})); }
            if (this.type) { await async.each(this.type, async v => await v.updateReferencesAsync({fnUpdateReferenceAsync})); }
            if (this.specialty) { await async.each(this.specialty, async v => await v.updateReferencesAsync({fnUpdateReferenceAsync})); }
            if (this.location) { await async.each(this.location, async v => await v.updateReferencesAsync({fnUpdateReferenceAsync})); }
            if (this.photo) { await this.photo.updateReferencesAsync({fnUpdateReferenceAsync}); }
            if (this.telecom) { await async.each(this.telecom, async v => await v.updateReferencesAsync({fnUpdateReferenceAsync})); }
            if (this.coverageArea) { await async.each(this.coverageArea, async v => await v.updateReferencesAsync({fnUpdateReferenceAsync})); }
            if (this.serviceProvisionCode) { await async.each(this.serviceProvisionCode, async v => await v.updateReferencesAsync({fnUpdateReferenceAsync})); }
            if (this.eligibility) { await async.each(this.eligibility, async v => await v.updateReferencesAsync({fnUpdateReferenceAsync})); }
            if (this.program) { await async.each(this.program, async v => await v.updateReferencesAsync({fnUpdateReferenceAsync})); }
            if (this.characteristic) { await async.each(this.characteristic, async v => await v.updateReferencesAsync({fnUpdateReferenceAsync})); }
            if (this.communication) { await async.each(this.communication, async v => await v.updateReferencesAsync({fnUpdateReferenceAsync})); }
            if (this.referralMethod) { await async.each(this.referralMethod, async v => await v.updateReferencesAsync({fnUpdateReferenceAsync})); }
            if (this.availableTime) { await async.each(this.availableTime, async v => await v.updateReferencesAsync({fnUpdateReferenceAsync})); }
            if (this.notAvailable) { await async.each(this.notAvailable, async v => await v.updateReferencesAsync({fnUpdateReferenceAsync})); }
            if (this.endpoint) { await async.each(this.endpoint, async v => await v.updateReferencesAsync({fnUpdateReferenceAsync})); }
    }

    /**
     * Returns JSON representation of entity
     * @return {Object}
     */
    toJSONInternal() {
        const {removeNull} = require('../../../../utils/nullRemover');
        const json = {
            resourceType: this.resourceType,
            id: this.id,
            meta: this.meta && this.meta.toJSONInternal(),
            implicitRules: this.implicitRules,
            language: this.language,
            text: this.text && this.text.toJSONInternal(),
            contained: this.contained && this.contained.map(v => v.toJSONInternal()),
            extension: this.extension && this.extension.map(v => v.toJSONInternal()),
            modifierExtension: this.modifierExtension && this.modifierExtension.map(v => v.toJSONInternal()),
            identifier: this.identifier && this.identifier.map(v => v.toJSONInternal()),
            active: this.active,
            providedBy: this.providedBy && this.providedBy.toJSONInternal(),
            category: this.category && this.category.map(v => v.toJSONInternal()),
            type: this.type && this.type.map(v => v.toJSONInternal()),
            specialty: this.specialty && this.specialty.map(v => v.toJSONInternal()),
            location: this.location && this.location.map(v => v.toJSONInternal()),
            name: this.name,
            comment: this.comment,
            extraDetails: this.extraDetails,
            photo: this.photo && this.photo.toJSONInternal(),
            telecom: this.telecom && this.telecom.map(v => v.toJSONInternal()),
            coverageArea: this.coverageArea && this.coverageArea.map(v => v.toJSONInternal()),
            serviceProvisionCode: this.serviceProvisionCode && this.serviceProvisionCode.map(v => v.toJSONInternal()),
            eligibility: this.eligibility && this.eligibility.map(v => v.toJSONInternal()),
            program: this.program && this.program.map(v => v.toJSONInternal()),
            characteristic: this.characteristic && this.characteristic.map(v => v.toJSONInternal()),
            communication: this.communication && this.communication.map(v => v.toJSONInternal()),
            referralMethod: this.referralMethod && this.referralMethod.map(v => v.toJSONInternal()),
            appointmentRequired: this.appointmentRequired,
            availableTime: this.availableTime && this.availableTime.map(v => v.toJSONInternal()),
            notAvailable: this.notAvailable && this.notAvailable.map(v => v.toJSONInternal()),
            availabilityExceptions: this.availabilityExceptions,
            endpoint: this.endpoint && this.endpoint.map(v => v.toJSONInternal())
        };


        if (this._access) {
            json._access = this._access;
        }
        if (this._sourceAssigningAuthority) {
            json._sourceAssigningAuthority = this._sourceAssigningAuthority;
        }
        if (this._uuid) {
            json._uuid = this._uuid;
        }
        if (this._sourceId) {
            json._sourceId = this._sourceId;
        }

        return removeNull(json);
    }
}

module.exports = HealthcareService;
