apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: nodefhirservermongo
  labels:
    app: busybox
spec:
  nodeSelector:
    node-role.kubernetes.io/master: ""
  # https://stackoverflow.com/questions/41999756/how-to-force-pods-deployments-to-master-nodes
  # https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
  tolerations:
  - key: node-role.kubernetes.io/master
    operator: Exists
    effect: NoSchedule
  containers:
  - name: busybox
    image: busybox
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
  restartPolicy: Always