// This file is auto-generated by generate_classes so do not edit manually

/**
ClaimResponse.Detail1
    This resource provides the adjudication details from the processing of a Claim
    resource.
*/
class ClaimResponseDetail1 {
    constructor(opts) {
        // Create an object to store all props
        Object.defineProperty(this, '__data', {
          value: {}
        }); // Define getters and setters as enumerable

        /**
         * @description None
         * @property {String|undefined}
        */
        Object.defineProperty(this, 'id', {
            enumerable: true,
            get: () => this.__data.id,
            set: value => {
                if (value === undefined || value === null) {
                    return;
                }
                this.__data.id = value;
            }
        });

        /**
         * @description May be used to represent additional information that is not part of the basic
    definition of the element. To make the use of extensions safe and manageable,
    there is a strict set of governance  applied to the definition and use of
    extensions. Though any implementer can define an extension, there is a set of
    requirements that SHALL be met as part of the definition of the extension.
         * @property {Extension[]|undefined}
        */
        Object.defineProperty(this, 'extension', {
            enumerable: true,
            get: () => this.__data.extension,
            set: value => {
                if (value === undefined || value === null) {
                    return;
                }
                let Extension = require('../extensions/extension.js');
                this.__data.extension = new Extension(value);
            }
        });

        /**
         * @description May be used to represent additional information that is not part of the basic
    definition of the element and that modifies the understanding of the element
    in which it is contained and/or the understanding of the containing element's
    descendants. Usually modifier elements provide negation or qualification. To
    make the use of extensions safe and manageable, there is a strict set of
    governance applied to the definition and use of extensions. Though any
    implementer can define an extension, there is a set of requirements that SHALL
    be met as part of the definition of the extension. Applications processing a
    resource are required to check for modifier extensions.

    Modifier extensions SHALL NOT change the meaning of any elements on Resource
    or DomainResource (including cannot change the meaning of modifierExtension
    itself).
         * @property {Extension[]|undefined}
        */
        Object.defineProperty(this, 'modifierExtension', {
            enumerable: true,
            get: () => this.__data.modifierExtension,
            set: value => {
                if (value === undefined || value === null) {
                    return;
                }
                let Extension = require('../extensions/extension.js');
                this.__data.modifierExtension = new Extension(value);
            }
        });

        /**
         * @description When the value is a group code then this item collects a set of related claim
    details, otherwise this contains the product, service, drug or other billing
    code for the item.
         * @property {CodeableConcept}
        */
        Object.defineProperty(this, 'productOrService', {
            enumerable: true,
            get: () => this.__data.productOrService,
            set: value => {
                if (value === undefined || value === null) {
                    return;
                }
                let CodeableConcept = require('../complex_types/codeableConcept.js');
                this.__data.productOrService = new CodeableConcept(value);
            }
        });

        /**
         * @description Item typification or modifiers codes to convey additional context for the
    product or service.
         * @property {CodeableConcept[]|undefined}
        */
        Object.defineProperty(this, 'modifier', {
            enumerable: true,
            get: () => this.__data.modifier,
            set: value => {
                if (value === undefined || value === null) {
                    return;
                }
                let CodeableConcept = require('../complex_types/codeableConcept.js');
                this.__data.modifier = new CodeableConcept(value);
            }
        });

        /**
         * @description The number of repetitions of a service or product.
         * @property {Quantity|undefined}
        */
        Object.defineProperty(this, 'quantity', {
            enumerable: true,
            get: () => this.__data.quantity,
            set: value => {
                if (value === undefined || value === null) {
                    return;
                }
                let Quantity = require('../complex_types/quantity.js');
                this.__data.quantity = new Quantity(value);
            }
        });

        /**
         * @description If the item is not a group then this is the fee for the product or service,
    otherwise this is the total of the fees for the details of the group.
         * @property {Money|undefined}
        */
        Object.defineProperty(this, 'unitPrice', {
            enumerable: true,
            get: () => this.__data.unitPrice,
            set: value => {
                if (value === undefined || value === null) {
                    return;
                }
                let Money = require('../complex_types/money.js');
                this.__data.unitPrice = new Money(value);
            }
        });

        /**
         * @description A real number that represents a multiplier used in determining the overall
    value of services delivered and/or goods received. The concept of a Factor
    allows for a discount or surcharge multiplier to be applied to a monetary
    amount.
         * @property {decimal|undefined}
        */
        Object.defineProperty(this, 'factor', {
            enumerable: true,
            get: () => this.__data.factor,
            set: value => {
                if (value === undefined || value === null) {
                    return;
                }
                let decimal = require('../simple_types/decimal.js');
                // eslint-disable-next-line new-cap
                this.__data.factor = new decimal(value);
            }
        });

        /**
         * @description The quantity times the unit price for an additional service or product or
    charge.
         * @property {Money|undefined}
        */
        Object.defineProperty(this, 'net', {
            enumerable: true,
            get: () => this.__data.net,
            set: value => {
                if (value === undefined || value === null) {
                    return;
                }
                let Money = require('../complex_types/money.js');
                this.__data.net = new Money(value);
            }
        });

        /**
         * @description The numbers associated with notes below which apply to the adjudication of
    this item.
         * @property {Int[]|undefined}
        */
        Object.defineProperty(this, 'noteNumber', {
            enumerable: true,
            get: () => this.__data.noteNumber,
            set: value => {
                if (value === undefined || value === null) {
                    return;
                }
                this.__data.noteNumber = value;
            }
        });

        /**
         * @description The adjudication results.
         * @property {ClaimResponseAdjudication[]}
        */
        Object.defineProperty(this, 'adjudication', {
            enumerable: true,
            get: () => this.__data.adjudication,
            set: value => {
                if (value === undefined || value === null) {
                    return;
                }
                let ClaimResponseAdjudication = require('../backbone_elements/claimResponseAdjudication.js');
                this.__data.adjudication = new ClaimResponseAdjudication(value);
            }
        });

        /**
         * @description The third-tier service adjudications for payor added services.
         * @property {ClaimResponseSubDetail1[]|undefined}
        */
        Object.defineProperty(this, 'subDetail', {
            enumerable: true,
            get: () => this.__data.subDetail,
            set: value => {
                if (value === undefined || value === null) {
                    return;
                }
                let ClaimResponseSubDetail1 = require('../backbone_elements/claimResponseSubDetail1.js');
                this.__data.subDetail = new ClaimResponseSubDetail1(value);
            }
        });

        Object.assign(this, opts); // Define a default non-writable resourceType property

        Object.defineProperty(this, 'resourceType', {
            value: 'ClaimResponseDetail1',
            enumerable: true,
            writable: false
        });
    }

    static get resourceType() {
        return 'ClaimResponseDetail1';
    }

    toJSON() {
        return {
            id: this.id,
            extension: this.extension && this.extension.toJSON(),
            modifierExtension: this.modifierExtension && this.modifierExtension.toJSON(),
            productOrService: this.productOrService && this.productOrService.toJSON(),
            modifier: this.modifier && this.modifier.toJSON(),
            quantity: this.quantity && this.quantity.toJSON(),
            unitPrice: this.unitPrice && this.unitPrice.toJSON(),
            factor: this.factor && this.factor.toJSON(),
            net: this.net && this.net.toJSON(),
            noteNumber: this.noteNumber,
            adjudication: this.adjudication && this.adjudication.toJSON(),
            subDetail: this.subDetail && this.subDetail.toJSON(),
        };
    }
}

module.exports = ClaimResponseDetail1;
