'use strict';

const { z } = require('zod/v4');
const { mcpToolsByResourceType } = require('./tools');
const { TYPE_VALUE_SYNTAX_HINTS } = require('./typeValueSyntaxHints');

const DEDICATED_RESOURCE_TYPES = new Set(Object.keys(mcpToolsByResourceType));

// Filter value syntax varies by the target search parameter's FHIR type, which this generic tool
// (unlike the dedicated per-resource tools) has no per-parameter schema to hang a type-specific hint
// off of -- so this cheat sheet is spelled out once, covering every type, instead of silently
// leaving callers to guess. Built from typeValueSyntaxHints.js -- generated by
// generatorScripts/mcp/generate_mcp_tools.py from the same TYPE_VALUE_SYNTAX_HINTS table that
// drives the dedicated tools' per-field hints -- rather than a hand-copied prose duplicate, so the
// two can't silently drift apart.
const FILTER_VALUE_SYNTAX_CHEAT_SHEET =
    'Value syntax by parameter type: ' +
    Object.entries(TYPE_VALUE_SYNTAX_HINTS).map(([type, hint]) => `${type} -- ${hint}`).join(' ') +
    " Comma-separate multiple values for the same filter to OR them. Append ':modifier' to a filter " +
    'key for: :missing, :not, :contains, :exact, :above, :below, :text, :of-type.';

const genericFhirSearchTool = {
    name: 'fhir_search',
    description:
        'Search any FHIR resource type not covered by a dedicated search_<resource> tool ' +
        `(dedicated tools already exist for: ${[...DEDICATED_RESOURCE_TYPES].sort().join(', ')}). ` +
        "Provide the target 'resourceType' plus any FHIR search parameters as string values in " +
        `'filters'. ${FILTER_VALUE_SYNTAX_CHEAT_SHEET}`,
    inputSchema: z.object({
        resourceType: z.string().describe(
            'The FHIR resource type to search, e.g. "Practitioner" or "Coverage". Do not use this ' +
            'for a resource type that already has a dedicated search_<resource> tool.'
        ),
        filters: z.record(z.string(), z.string()).optional().describe(
            'Search parameter name/value pairs, e.g. { "identifier": "12345", "status": "active" }. ' +
            FILTER_VALUE_SYNTAX_CHEAT_SHEET
        )
    })
};

module.exports = { genericFhirSearchTool, DEDICATED_RESOURCE_TYPES };
