// This file is auto-generated by generate_serializers so do not edit manually
const BaseSerializer = require('../customSerializers/baseSerializer.js');

/** @type {import('../complexTypes/meta.js')} */
let MetaSerializer;
/** @type {import('../complexTypes/narrative.js')} */
let NarrativeSerializer;
/** @type {import('../customSerializers/resourceContainer.js')} */
let ResourceContainerSerializer;
/** @type {import('../complexTypes/extension.js')} */
let ExtensionSerializer;
/** @type {import('../complexTypes/identifier.js')} */
let IdentifierSerializer;
/** @type {import('../complexTypes/reference.js')} */
let ReferenceSerializer;
/** @type {import('../complexTypes/period.js')} */
let PeriodSerializer;
/** @type {import('../complexTypes/codeableConcept.js')} */
let CodeableConceptSerializer;
/** @type {import('../backboneElements/measureReportGroup.js')} */
let MeasureReportGroupSerializer;

class MeasureReportSerializer extends BaseSerializer {
    // Private cache for lazy-loaded property configs
    #configCache = {};

    fhirPropertyToSerializerMap = {
        id: null,
        meta: () => {
            if (!this.#configCache['meta']) {
                if (!MetaSerializer) {
                    MetaSerializer = require('../complexTypes/meta.js');
                }
                this.#configCache['meta'] = {
                    serializeFunction: 'serialize',
                    serializerClass: MetaSerializer
                };
            }
            return this.#configCache['meta'];
        },
        implicitRules: null,
        language: null,
        text: () => {
            if (!this.#configCache['text']) {
                if (!NarrativeSerializer) {
                    NarrativeSerializer = require('../complexTypes/narrative.js');
                }
                this.#configCache['text'] = {
                    serializeFunction: 'serialize',
                    serializerClass: NarrativeSerializer
                };
            }
            return this.#configCache['text'];
        },
        contained: () => {
            if (!this.#configCache['contained']) {
                if (!ResourceContainerSerializer) {
                    ResourceContainerSerializer = require('../customSerializers/resourceContainer.js');
                }
                this.#configCache['contained'] = {
                    serializeFunction: 'serializeArray'
                };
            }
            return this.#configCache['contained'];
        },
        extension: () => {
            if (!this.#configCache['extension']) {
                if (!ExtensionSerializer) {
                    ExtensionSerializer = require('../complexTypes/extension.js');
                }
                this.#configCache['extension'] = {
                    serializeFunction: 'serializeArray',
                    serializerClass: ExtensionSerializer
                };
            }
            return this.#configCache['extension'];
        },
        modifierExtension: () => {
            if (!this.#configCache['modifierExtension']) {
                if (!ExtensionSerializer) {
                    ExtensionSerializer = require('../complexTypes/extension.js');
                }
                this.#configCache['modifierExtension'] = {
                    serializeFunction: 'serializeArray',
                    serializerClass: ExtensionSerializer
                };
            }
            return this.#configCache['modifierExtension'];
        },
        identifier: () => {
            if (!this.#configCache['identifier']) {
                if (!IdentifierSerializer) {
                    IdentifierSerializer = require('../complexTypes/identifier.js');
                }
                this.#configCache['identifier'] = {
                    serializeFunction: 'serializeArray',
                    serializerClass: IdentifierSerializer
                };
            }
            return this.#configCache['identifier'];
        },
        status: null,
        type: null,
        measure: null,
        subject: () => {
            if (!this.#configCache['subject']) {
                if (!ReferenceSerializer) {
                    ReferenceSerializer = require('../complexTypes/reference.js');
                }
                this.#configCache['subject'] = {
                    serializeFunction: 'serialize',
                    serializerClass: ReferenceSerializer
                };
            }
            return this.#configCache['subject'];
        },
        date: null,
        reporter: () => {
            if (!this.#configCache['reporter']) {
                if (!ReferenceSerializer) {
                    ReferenceSerializer = require('../complexTypes/reference.js');
                }
                this.#configCache['reporter'] = {
                    serializeFunction: 'serialize',
                    serializerClass: ReferenceSerializer
                };
            }
            return this.#configCache['reporter'];
        },
        period: () => {
            if (!this.#configCache['period']) {
                if (!PeriodSerializer) {
                    PeriodSerializer = require('../complexTypes/period.js');
                }
                this.#configCache['period'] = {
                    serializeFunction: 'serialize',
                    serializerClass: PeriodSerializer
                };
            }
            return this.#configCache['period'];
        },
        improvementNotation: () => {
            if (!this.#configCache['improvementNotation']) {
                if (!CodeableConceptSerializer) {
                    CodeableConceptSerializer = require('../complexTypes/codeableConcept.js');
                }
                this.#configCache['improvementNotation'] = {
                    serializeFunction: 'serialize',
                    serializerClass: CodeableConceptSerializer
                };
            }
            return this.#configCache['improvementNotation'];
        },
        group: () => {
            if (!this.#configCache['group']) {
                if (!MeasureReportGroupSerializer) {
                    MeasureReportGroupSerializer = require('../backboneElements/measureReportGroup.js');
                }
                this.#configCache['group'] = {
                    serializeFunction: 'serializeArray',
                    serializerClass: MeasureReportGroupSerializer
                };
            }
            return this.#configCache['group'];
        },
        evaluatedResource: () => {
            if (!this.#configCache['evaluatedResource']) {
                if (!ReferenceSerializer) {
                    ReferenceSerializer = require('../complexTypes/reference.js');
                }
                this.#configCache['evaluatedResource'] = {
                    serializeFunction: 'serializeArray',
                    serializerClass: ReferenceSerializer
                };
            }
            return this.#configCache['evaluatedResource'];
        },
        resourceType: null
    };

    allPropertyToSerializerMap = {
        id: null,
        meta: () => {
            if (!this.#configCache['meta']) {
                if (!MetaSerializer) {
                    MetaSerializer = require('../complexTypes/meta.js');
                }
                this.#configCache['meta'] = {
                    serializeFunction: 'serialize',
                    serializerClass: MetaSerializer
                };
            }
            return this.#configCache['meta'];
        },
        implicitRules: null,
        language: null,
        text: () => {
            if (!this.#configCache['text']) {
                if (!NarrativeSerializer) {
                    NarrativeSerializer = require('../complexTypes/narrative.js');
                }
                this.#configCache['text'] = {
                    serializeFunction: 'serialize',
                    serializerClass: NarrativeSerializer
                };
            }
            return this.#configCache['text'];
        },
        contained: () => {
            if (!this.#configCache['contained']) {
                if (!ResourceContainerSerializer) {
                    ResourceContainerSerializer = require('../customSerializers/resourceContainer.js');
                }
                this.#configCache['contained'] = {
                    serializeFunction: 'serializeArray'
                };
            }
            return this.#configCache['contained'];
        },
        extension: () => {
            if (!this.#configCache['extension']) {
                if (!ExtensionSerializer) {
                    ExtensionSerializer = require('../complexTypes/extension.js');
                }
                this.#configCache['extension'] = {
                    serializeFunction: 'serializeArray',
                    serializerClass: ExtensionSerializer
                };
            }
            return this.#configCache['extension'];
        },
        modifierExtension: () => {
            if (!this.#configCache['modifierExtension']) {
                if (!ExtensionSerializer) {
                    ExtensionSerializer = require('../complexTypes/extension.js');
                }
                this.#configCache['modifierExtension'] = {
                    serializeFunction: 'serializeArray',
                    serializerClass: ExtensionSerializer
                };
            }
            return this.#configCache['modifierExtension'];
        },
        identifier: () => {
            if (!this.#configCache['identifier']) {
                if (!IdentifierSerializer) {
                    IdentifierSerializer = require('../complexTypes/identifier.js');
                }
                this.#configCache['identifier'] = {
                    serializeFunction: 'serializeArray',
                    serializerClass: IdentifierSerializer
                };
            }
            return this.#configCache['identifier'];
        },
        status: null,
        type: null,
        measure: null,
        subject: () => {
            if (!this.#configCache['subject']) {
                if (!ReferenceSerializer) {
                    ReferenceSerializer = require('../complexTypes/reference.js');
                }
                this.#configCache['subject'] = {
                    serializeFunction: 'serialize',
                    serializerClass: ReferenceSerializer
                };
            }
            return this.#configCache['subject'];
        },
        date: null,
        reporter: () => {
            if (!this.#configCache['reporter']) {
                if (!ReferenceSerializer) {
                    ReferenceSerializer = require('../complexTypes/reference.js');
                }
                this.#configCache['reporter'] = {
                    serializeFunction: 'serialize',
                    serializerClass: ReferenceSerializer
                };
            }
            return this.#configCache['reporter'];
        },
        period: () => {
            if (!this.#configCache['period']) {
                if (!PeriodSerializer) {
                    PeriodSerializer = require('../complexTypes/period.js');
                }
                this.#configCache['period'] = {
                    serializeFunction: 'serialize',
                    serializerClass: PeriodSerializer
                };
            }
            return this.#configCache['period'];
        },
        improvementNotation: () => {
            if (!this.#configCache['improvementNotation']) {
                if (!CodeableConceptSerializer) {
                    CodeableConceptSerializer = require('../complexTypes/codeableConcept.js');
                }
                this.#configCache['improvementNotation'] = {
                    serializeFunction: 'serialize',
                    serializerClass: CodeableConceptSerializer
                };
            }
            return this.#configCache['improvementNotation'];
        },
        group: () => {
            if (!this.#configCache['group']) {
                if (!MeasureReportGroupSerializer) {
                    MeasureReportGroupSerializer = require('../backboneElements/measureReportGroup.js');
                }
                this.#configCache['group'] = {
                    serializeFunction: 'serializeArray',
                    serializerClass: MeasureReportGroupSerializer
                };
            }
            return this.#configCache['group'];
        },
        evaluatedResource: () => {
            if (!this.#configCache['evaluatedResource']) {
                if (!ReferenceSerializer) {
                    ReferenceSerializer = require('../complexTypes/reference.js');
                }
                this.#configCache['evaluatedResource'] = {
                    serializeFunction: 'serializeArray',
                    serializerClass: ReferenceSerializer
                };
            }
            return this.#configCache['evaluatedResource'];
        },
        resourceType: null,
        _access: null,
        _sourceAssigningAuthority: null,
        _uuid: null,
        _sourceId: null
    };
}

module.exports = new MeasureReportSerializer();
