/* eslint-disable no-unused-vars */
// This file is auto-generated by generate_classes so do not edit manually

const Element = require('../complex_types/element');


/**
AuditEvent.Agent
    A record of an event made for purposes of maintaining a security log. Typical
    uses include detection of intrusion attempts and monitoring for inappropriate
    usage.
*/
class AuditEventAgent extends Element {
    /**
     * @param {String|undefined} [id],
     * @param {Extension[]|undefined} [extension],
     * @param {Extension[]|undefined} [modifierExtension],
     * @param {CodeableConcept|undefined} [type],
     * @param {CodeableConcept[]|undefined} [role],
     * @param {Reference|undefined} [who],
     * @param {String|undefined} [altId],
     * @param {String|undefined} [name],
     * @param {Boolean} requestor,
     * @param {Reference|undefined} [location],
     * @param {uri[]|undefined} [policy],
     * @param {Coding|undefined} [media],
     * @param {AuditEventNetwork|undefined} [network],
     * @param {CodeableConcept[]|undefined} [purposeOfUse],
    */
    constructor(
        {
            id,
            extension,
            modifierExtension,
            type,
            role,
            who,
            altId,
            name,
            requestor,
            location,
            policy,
            media,
            network,
            purposeOfUse,
        }
    ) {
        super({});

        // ---- Define getters and setters as enumerable ---

        /**
         * @description None
         * @property {String|undefined}
        */
        Object.defineProperty(this, 'id', {
            enumerable: true,
            get: () => this.__data.id,
            set: valueProvided => {
                if (valueProvided === undefined || valueProvided === null) {
                    return;
                }
                this.__data.id = valueProvided;
            }
        });

        /**
         * @description May be used to represent additional information that is not part of the basic
    definition of the element. To make the use of extensions safe and manageable,
    there is a strict set of governance  applied to the definition and use of
    extensions. Though any implementer can define an extension, there is a set of
    requirements that SHALL be met as part of the definition of the extension.
         * @property {Extension[]|undefined}
        */
        Object.defineProperty(this, 'extension', {
            enumerable: true,
            get: () => this.__data.extension,
            set: valueProvided => {
                if (valueProvided === undefined || valueProvided === null) {
                    return;
                }
                let Extension = require('../extensions/extension.js');
                this.__data.extension = Array.isArray(valueProvided) ? valueProvided.map(v => new Extension(v)) : [new Extension(valueProvided)];
            }
        });

        /**
         * @description May be used to represent additional information that is not part of the basic
    definition of the element and that modifies the understanding of the element
    in which it is contained and/or the understanding of the containing element's
    descendants. Usually modifier elements provide negation or qualification. To
    make the use of extensions safe and manageable, there is a strict set of
    governance applied to the definition and use of extensions. Though any
    implementer can define an extension, there is a set of requirements that SHALL
    be met as part of the definition of the extension. Applications processing a
    resource are required to check for modifier extensions.

    Modifier extensions SHALL NOT change the meaning of any elements on Resource
    or DomainResource (including cannot change the meaning of modifierExtension
    itself).
         * @property {Extension[]|undefined}
        */
        Object.defineProperty(this, 'modifierExtension', {
            enumerable: true,
            get: () => this.__data.modifierExtension,
            set: valueProvided => {
                if (valueProvided === undefined || valueProvided === null) {
                    return;
                }
                let Extension = require('../extensions/extension.js');
                this.__data.modifierExtension = Array.isArray(valueProvided) ? valueProvided.map(v => new Extension(v)) : [new Extension(valueProvided)];
            }
        });

        /**
         * @description Specification of the participation type the user plays when performing the
    event.
         * @property {CodeableConcept|undefined}
        */
        Object.defineProperty(this, 'type', {
            enumerable: true,
            get: () => this.__data.type,
            set: valueProvided => {
                if (valueProvided === undefined || valueProvided === null) {
                    return;
                }
                let CodeableConcept = require('../complex_types/codeableConcept.js');
                this.__data.type = new CodeableConcept(valueProvided);
            }
        });

        /**
         * @description The security role that the user was acting under, that come from local codes
    defined by the access control security system (e.g. RBAC, ABAC) used in the
    local context.
         * @property {CodeableConcept[]|undefined}
        */
        Object.defineProperty(this, 'role', {
            enumerable: true,
            get: () => this.__data.role,
            set: valueProvided => {
                if (valueProvided === undefined || valueProvided === null) {
                    return;
                }
                let CodeableConcept = require('../complex_types/codeableConcept.js');
                this.__data.role = Array.isArray(valueProvided) ? valueProvided.map(v => new CodeableConcept(v)) : [new CodeableConcept(valueProvided)];
            }
        });

        /**
         * @description Reference to who this agent is that was involved in the event.
         * @property {Reference|undefined}
        */
        Object.defineProperty(this, 'who', {
            enumerable: true,
            get: () => this.__data.who,
            set: valueProvided => {
                if (valueProvided === undefined || valueProvided === null) {
                    return;
                }
                let Reference = require('../complex_types/reference.js');
                this.__data.who = new Reference(valueProvided);
            }
        });

        /**
         * @description Alternative agent Identifier. For a human, this should be a user identifier
    text string from authentication system. This identifier would be one known to
    a common authentication system (e.g. single sign-on), if available.
         * @property {String|undefined}
        */
        Object.defineProperty(this, 'altId', {
            enumerable: true,
            get: () => this.__data.altId,
            set: valueProvided => {
                if (valueProvided === undefined || valueProvided === null) {
                    return;
                }
                this.__data.altId = valueProvided;
            }
        });

        /**
         * @description Human-meaningful name for the agent.
         * @property {String|undefined}
        */
        Object.defineProperty(this, 'name', {
            enumerable: true,
            get: () => this.__data.name,
            set: valueProvided => {
                if (valueProvided === undefined || valueProvided === null) {
                    return;
                }
                this.__data.name = valueProvided;
            }
        });

        /**
         * @description Indicator that the user is or is not the requestor, or initiator, for the
    event being audited.
         * @property {Boolean}
        */
        Object.defineProperty(this, 'requestor', {
            enumerable: true,
            get: () => this.__data.requestor,
            set: valueProvided => {
                if (valueProvided === undefined || valueProvided === null) {
                    return;
                }
                this.__data.requestor = valueProvided;
            }
        });

        /**
         * @description Where the event occurred.
         * @property {Reference|undefined}
        */
        Object.defineProperty(this, 'location', {
            enumerable: true,
            get: () => this.__data.location,
            set: valueProvided => {
                if (valueProvided === undefined || valueProvided === null) {
                    return;
                }
                let Reference = require('../complex_types/reference.js');
                this.__data.location = new Reference(valueProvided);
            }
        });

        /**
         * @description The policy or plan that authorized the activity being recorded. Typically, a
    single activity may have multiple applicable policies, such as patient
    consent, guarantor funding, etc. The policy would also indicate the security
    token used.
         * @property {uri[]|undefined}
        */
        Object.defineProperty(this, 'policy', {
            enumerable: true,
            get: () => this.__data.policy,
            set: valueProvided => {
                if (valueProvided === undefined || valueProvided === null) {
                    return;
                }
                this.__data.policy = Array.isArray(valueProvided) ? valueProvided.map(v => v) : [valueProvided];
            }
        });

        /**
         * @description Type of media involved. Used when the event is about exporting/importing onto
    media.
         * @property {Coding|undefined}
        */
        Object.defineProperty(this, 'media', {
            enumerable: true,
            get: () => this.__data.media,
            set: valueProvided => {
                if (valueProvided === undefined || valueProvided === null) {
                    return;
                }
                let Coding = require('../complex_types/coding.js');
                this.__data.media = new Coding(valueProvided);
            }
        });

        /**
         * @description Logical network location for application activity, if the activity has a
    network location.
         * @property {AuditEventNetwork|undefined}
        */
        Object.defineProperty(this, 'network', {
            enumerable: true,
            get: () => this.__data.network,
            set: valueProvided => {
                if (valueProvided === undefined || valueProvided === null) {
                    return;
                }
                let AuditEventNetwork = require('../backbone_elements/auditEventNetwork.js');
                this.__data.network = new AuditEventNetwork(valueProvided);
            }
        });

        /**
         * @description The reason (purpose of use), specific to this agent, that was used during the
    event being recorded.
         * @property {CodeableConcept[]|undefined}
        */
        Object.defineProperty(this, 'purposeOfUse', {
            enumerable: true,
            get: () => this.__data.purposeOfUse,
            set: valueProvided => {
                if (valueProvided === undefined || valueProvided === null) {
                    return;
                }
                let CodeableConcept = require('../complex_types/codeableConcept.js');
                this.__data.purposeOfUse = Array.isArray(valueProvided) ? valueProvided.map(v => new CodeableConcept(v)) : [new CodeableConcept(valueProvided)];
            }
        });

        Object.assign(this, {
            id,
            extension,
            modifierExtension,
            type,
            role,
            who,
            altId,
            name,
            requestor,
            location,
            policy,
            media,
            network,
            purposeOfUse,
        });

        // Define a default non-writable resourceType property

        Object.defineProperty(this, 'resourceType', {
            value: 'AuditEventAgent',
            enumerable: true,
            writable: false
        });
    }

    static get resourceType() {
        return 'AuditEventAgent';
    }

    toJSON() {
        return {
            id: this.id,
            extension: this.extension && this.extension.map(v => v.toJSON()),
            modifierExtension: this.modifierExtension && this.modifierExtension.map(v => v.toJSON()),
            type: this.type && this.type.toJSON(),
            role: this.role && this.role.map(v => v.toJSON()),
            who: this.who && this.who.toJSON(),
            altId: this.altId,
            name: this.name,
            requestor: this.requestor,
            location: this.location && this.location.toJSON(),
            policy: this.policy,
            media: this.media && this.media.toJSON(),
            network: this.network && this.network.toJSON(),
            purposeOfUse: this.purposeOfUse && this.purposeOfUse.map(v => v.toJSON()),
        };
    }
}

module.exports = AuditEventAgent;
