/* eslint-disable no-unused-vars */
// This file is auto-generated by generate_classes so do not edit manually

const Resource = require('../resources/resource');


/**
OperationOutcome.Issue
    A collection of error, warning, or information messages that result from a
    system action.
*/
class OperationOutcomeIssue extends Resource {
    /**
     * @param {String|undefined} [id],
     * @param {Extension[]|undefined} [extension],
     * @param {Extension[]|undefined} [modifierExtension],
     * @param {code} severity,
     * @param {code} code,
     * @param {CodeableConcept|undefined} [details],
     * @param {String|undefined} [diagnostics],
     * @param {String[]|undefined} [location],
     * @param {String[]|undefined} [expression],
    */
    constructor(
        {
            id,
            extension,
            modifierExtension,
            severity,
            code,
            details,
            diagnostics,
            location,
            expression,
        }
    ) {
        super({});
        // Create an object to store all props
        Object.defineProperty(this, '__data', {
          value: {}
        }); // Define getters and setters as enumerable

        /**
         * @description None
         * @property {String|undefined}
        */
        Object.defineProperty(this, 'id', {
            enumerable: true,
            get: () => this.__data.id,
            set: valueProvided => {
                if (valueProvided === undefined || valueProvided === null) {
                    return;
                }
                this.__data.id = valueProvided;
            }
        });

        /**
         * @description May be used to represent additional information that is not part of the basic
    definition of the element. To make the use of extensions safe and manageable,
    there is a strict set of governance  applied to the definition and use of
    extensions. Though any implementer can define an extension, there is a set of
    requirements that SHALL be met as part of the definition of the extension.
         * @property {Extension[]|undefined}
        */
        Object.defineProperty(this, 'extension', {
            enumerable: true,
            get: () => this.__data.extension,
            set: valueProvided => {
                if (valueProvided === undefined || valueProvided === null) {
                    return;
                }
                let Extension = require('../extensions/extension.js');
                this.__data.extension = Array.isArray(valueProvided) ? valueProvided.map(v => new Extension(v)) : [new Extension(valueProvided)];
            }
        });

        /**
         * @description May be used to represent additional information that is not part of the basic
    definition of the element and that modifies the understanding of the element
    in which it is contained and/or the understanding of the containing element's
    descendants. Usually modifier elements provide negation or qualification. To
    make the use of extensions safe and manageable, there is a strict set of
    governance applied to the definition and use of extensions. Though any
    implementer can define an extension, there is a set of requirements that SHALL
    be met as part of the definition of the extension. Applications processing a
    resource are required to check for modifier extensions.

    Modifier extensions SHALL NOT change the meaning of any elements on Resource
    or DomainResource (including cannot change the meaning of modifierExtension
    itself).
         * @property {Extension[]|undefined}
        */
        Object.defineProperty(this, 'modifierExtension', {
            enumerable: true,
            get: () => this.__data.modifierExtension,
            set: valueProvided => {
                if (valueProvided === undefined || valueProvided === null) {
                    return;
                }
                let Extension = require('../extensions/extension.js');
                this.__data.modifierExtension = Array.isArray(valueProvided) ? valueProvided.map(v => new Extension(v)) : [new Extension(valueProvided)];
            }
        });

        /**
         * @description Indicates whether the issue indicates a variation from successful processing.
         * @property {code}
        */
        Object.defineProperty(this, 'severity', {
            enumerable: true,
            get: () => this.__data.severity,
            set: valueProvided => {
                if (valueProvided === undefined || valueProvided === null) {
                    return;
                }
                this.__data.severity = valueProvided;
            }
        });

        /**
         * @description Describes the type of the issue. The system that creates an OperationOutcome
    SHALL choose the most applicable code from the IssueType value set, and may
    additional provide its own code for the error in the details element.
         * @property {code}
        */
        Object.defineProperty(this, 'code', {
            enumerable: true,
            get: () => this.__data.code,
            set: valueProvided => {
                if (valueProvided === undefined || valueProvided === null) {
                    return;
                }
                this.__data.code = valueProvided;
            }
        });

        /**
         * @description Additional details about the error. This may be a text description of the
    error or a system code that identifies the error.
         * @property {CodeableConcept|undefined}
        */
        Object.defineProperty(this, 'details', {
            enumerable: true,
            get: () => this.__data.details,
            set: valueProvided => {
                if (valueProvided === undefined || valueProvided === null) {
                    return;
                }
                let CodeableConcept = require('../complex_types/codeableConcept.js');
                this.__data.details = new CodeableConcept(valueProvided);
            }
        });

        /**
         * @description Additional diagnostic information about the issue.
         * @property {String|undefined}
        */
        Object.defineProperty(this, 'diagnostics', {
            enumerable: true,
            get: () => this.__data.diagnostics,
            set: valueProvided => {
                if (valueProvided === undefined || valueProvided === null) {
                    return;
                }
                this.__data.diagnostics = valueProvided;
            }
        });

        /**
         * @description This element is deprecated because it is XML specific. It is replaced by
    issue.expression, which is format independent, and simpler to parse.

    For resource issues, this will be a simple XPath limited to element names,
    repetition indicators and the default child accessor that identifies one of
    the elements in the resource that caused this issue to be raised.  For HTTP
    errors, will be "http." + the parameter name.
         * @property {String[]|undefined}
        */
        Object.defineProperty(this, 'location', {
            enumerable: true,
            get: () => this.__data.location,
            set: valueProvided => {
                if (valueProvided === undefined || valueProvided === null) {
                    return;
                }
                this.__data.location = Array.isArray(valueProvided) ? valueProvided.map(v => v) : [valueProvided];
            }
        });

        /**
         * @description A [simple subset of FHIRPath](fhirpath.html#simple) limited to element names,
    repetition indicators and the default child accessor that identifies one of
    the elements in the resource that caused this issue to be raised.
         * @property {String[]|undefined}
        */
        Object.defineProperty(this, 'expression', {
            enumerable: true,
            get: () => this.__data.expression,
            set: valueProvided => {
                if (valueProvided === undefined || valueProvided === null) {
                    return;
                }
                this.__data.expression = Array.isArray(valueProvided) ? valueProvided.map(v => v) : [valueProvided];
            }
        });

        Object.assign(this, {
            id,
            extension,
            modifierExtension,
            severity,
            code,
            details,
            diagnostics,
            location,
            expression,
        });

        // Define a default non-writable resourceType property

        Object.defineProperty(this, 'resourceType', {
            value: 'OperationOutcomeIssue',
            enumerable: true,
            writable: false
        });
    }

    static get resourceType() {
        return 'OperationOutcomeIssue';
    }

    toJSON() {
        return {
            id: this.id,
            extension: this.extension && this.extension.map(v => v.toJSON()),
            modifierExtension: this.modifierExtension && this.modifierExtension.map(v => v.toJSON()),
            severity: this.severity,
            code: this.code,
            details: this.details && this.details.toJSON(),
            diagnostics: this.diagnostics,
            location: this.location,
            expression: this.expression,
        };
    }
}

module.exports = OperationOutcomeIssue;
