/* eslint-disable no-unused-vars */
// This file is auto-generated by generate_classes so do not edit manually

const Element = require('../complex_types/element');


/**
ProdCharacteristic
    The marketing status describes the date when a medicinal product is actually
    put on the market or the date as of which it is no longer available.
    If the element is present, it must have a value for at least one of the
    defined elements, an @id referenced from the Narrative, or extensions
*/
class ProdCharacteristic extends Element {
    /**
     * @param {String|undefined} [id],
     * @param {Extension[]|undefined} [extension],
     * @param {Extension[]|undefined} [modifierExtension],
     * @param {Quantity|undefined} [height],
     * @param {Quantity|undefined} [width],
     * @param {Quantity|undefined} [depth],
     * @param {Quantity|undefined} [weight],
     * @param {Quantity|undefined} [nominalVolume],
     * @param {Quantity|undefined} [externalDiameter],
     * @param {String|undefined} [shape],
     * @param {String[]|undefined} [color],
     * @param {String[]|undefined} [imprint],
     * @param {Attachment[]|undefined} [image],
     * @param {CodeableConcept|undefined} [scoring],
    */
    constructor(
        {
            id,
            extension,
            modifierExtension,
            height,
            width,
            depth,
            weight,
            nominalVolume,
            externalDiameter,
            shape,
            color,
            imprint,
            image,
            scoring,
        }
    ) {
        super({});

        // ---- Define getters and setters as enumerable ---

        /**
         * @description None
         * @property {String|undefined}
        */
        Object.defineProperty(this, 'id', {
            // https://www.w3schools.com/js/js_object_es5.asp
            enumerable: true,
            configurable: true,
            get: () => this.__data.id,
            set: valueProvided => {
                if (valueProvided === undefined || valueProvided === null || (Array.isArray(valueProvided) && valueProvided.length === 0)) {
                    return;
                }
                this.__data.id = valueProvided;
            }
        });

        /**
         * @description May be used to represent additional information that is not part of the basic
    definition of the element. To make the use of extensions safe and manageable,
    there is a strict set of governance  applied to the definition and use of
    extensions. Though any implementer can define an extension, there is a set of
    requirements that SHALL be met as part of the definition of the extension.
         * @property {Extension[]|undefined}
        */
        Object.defineProperty(this, 'extension', {
            // https://www.w3schools.com/js/js_object_es5.asp
            enumerable: true,
            configurable: true,
            get: () => this.__data.extension,
            set: valueProvided => {
                if (valueProvided === undefined || valueProvided === null || (Array.isArray(valueProvided) && valueProvided.length === 0)) {
                    return;
                }
                let Extension = require('../extensions/extension.js');
                this.__data.extension = Array.isArray(valueProvided) ? valueProvided.map(v => new Extension(v)) : [new Extension(valueProvided)];
            }
        });

        /**
         * @description May be used to represent additional information that is not part of the basic
    definition of the element and that modifies the understanding of the element
    in which it is contained and/or the understanding of the containing element's
    descendants. Usually modifier elements provide negation or qualification. To
    make the use of extensions safe and manageable, there is a strict set of
    governance applied to the definition and use of extensions. Though any
    implementer can define an extension, there is a set of requirements that SHALL
    be met as part of the definition of the extension. Applications processing a
    resource are required to check for modifier extensions.

    Modifier extensions SHALL NOT change the meaning of any elements on Resource
    or DomainResource (including cannot change the meaning of modifierExtension
    itself).
         * @property {Extension[]|undefined}
        */
        Object.defineProperty(this, 'modifierExtension', {
            // https://www.w3schools.com/js/js_object_es5.asp
            enumerable: true,
            configurable: true,
            get: () => this.__data.modifierExtension,
            set: valueProvided => {
                if (valueProvided === undefined || valueProvided === null || (Array.isArray(valueProvided) && valueProvided.length === 0)) {
                    return;
                }
                let Extension = require('../extensions/extension.js');
                this.__data.modifierExtension = Array.isArray(valueProvided) ? valueProvided.map(v => new Extension(v)) : [new Extension(valueProvided)];
            }
        });

        /**
         * @description Where applicable, the height can be specified using a numerical value and its
    unit of measurement The unit of measurement shall be specified in accordance
    with ISO 11240 and the resulting terminology The symbol and the symbol
    identifier shall be used.
         * @property {Quantity|undefined}
        */
        Object.defineProperty(this, 'height', {
            // https://www.w3schools.com/js/js_object_es5.asp
            enumerable: true,
            configurable: true,
            get: () => this.__data.height,
            set: valueProvided => {
                if (valueProvided === undefined || valueProvided === null || (Array.isArray(valueProvided) && valueProvided.length === 0)) {
                    return;
                }
                let Quantity = require('../complex_types/quantity.js');
                this.__data.height = new Quantity(valueProvided);
            }
        });

        /**
         * @description Where applicable, the width can be specified using a numerical value and its
    unit of measurement The unit of measurement shall be specified in accordance
    with ISO 11240 and the resulting terminology The symbol and the symbol
    identifier shall be used.
         * @property {Quantity|undefined}
        */
        Object.defineProperty(this, 'width', {
            // https://www.w3schools.com/js/js_object_es5.asp
            enumerable: true,
            configurable: true,
            get: () => this.__data.width,
            set: valueProvided => {
                if (valueProvided === undefined || valueProvided === null || (Array.isArray(valueProvided) && valueProvided.length === 0)) {
                    return;
                }
                let Quantity = require('../complex_types/quantity.js');
                this.__data.width = new Quantity(valueProvided);
            }
        });

        /**
         * @description Where applicable, the depth can be specified using a numerical value and its
    unit of measurement The unit of measurement shall be specified in accordance
    with ISO 11240 and the resulting terminology The symbol and the symbol
    identifier shall be used.
         * @property {Quantity|undefined}
        */
        Object.defineProperty(this, 'depth', {
            // https://www.w3schools.com/js/js_object_es5.asp
            enumerable: true,
            configurable: true,
            get: () => this.__data.depth,
            set: valueProvided => {
                if (valueProvided === undefined || valueProvided === null || (Array.isArray(valueProvided) && valueProvided.length === 0)) {
                    return;
                }
                let Quantity = require('../complex_types/quantity.js');
                this.__data.depth = new Quantity(valueProvided);
            }
        });

        /**
         * @description Where applicable, the weight can be specified using a numerical value and its
    unit of measurement The unit of measurement shall be specified in accordance
    with ISO 11240 and the resulting terminology The symbol and the symbol
    identifier shall be used.
         * @property {Quantity|undefined}
        */
        Object.defineProperty(this, 'weight', {
            // https://www.w3schools.com/js/js_object_es5.asp
            enumerable: true,
            configurable: true,
            get: () => this.__data.weight,
            set: valueProvided => {
                if (valueProvided === undefined || valueProvided === null || (Array.isArray(valueProvided) && valueProvided.length === 0)) {
                    return;
                }
                let Quantity = require('../complex_types/quantity.js');
                this.__data.weight = new Quantity(valueProvided);
            }
        });

        /**
         * @description Where applicable, the nominal volume can be specified using a numerical value
    and its unit of measurement The unit of measurement shall be specified in
    accordance with ISO 11240 and the resulting terminology The symbol and the
    symbol identifier shall be used.
         * @property {Quantity|undefined}
        */
        Object.defineProperty(this, 'nominalVolume', {
            // https://www.w3schools.com/js/js_object_es5.asp
            enumerable: true,
            configurable: true,
            get: () => this.__data.nominalVolume,
            set: valueProvided => {
                if (valueProvided === undefined || valueProvided === null || (Array.isArray(valueProvided) && valueProvided.length === 0)) {
                    return;
                }
                let Quantity = require('../complex_types/quantity.js');
                this.__data.nominalVolume = new Quantity(valueProvided);
            }
        });

        /**
         * @description Where applicable, the external diameter can be specified using a numerical
    value and its unit of measurement The unit of measurement shall be specified
    in accordance with ISO 11240 and the resulting terminology The symbol and the
    symbol identifier shall be used.
         * @property {Quantity|undefined}
        */
        Object.defineProperty(this, 'externalDiameter', {
            // https://www.w3schools.com/js/js_object_es5.asp
            enumerable: true,
            configurable: true,
            get: () => this.__data.externalDiameter,
            set: valueProvided => {
                if (valueProvided === undefined || valueProvided === null || (Array.isArray(valueProvided) && valueProvided.length === 0)) {
                    return;
                }
                let Quantity = require('../complex_types/quantity.js');
                this.__data.externalDiameter = new Quantity(valueProvided);
            }
        });

        /**
         * @description Where applicable, the shape can be specified An appropriate controlled
    vocabulary shall be used The term and the term identifier shall be used.
         * @property {String|undefined}
        */
        Object.defineProperty(this, 'shape', {
            // https://www.w3schools.com/js/js_object_es5.asp
            enumerable: true,
            configurable: true,
            get: () => this.__data.shape,
            set: valueProvided => {
                if (valueProvided === undefined || valueProvided === null || (Array.isArray(valueProvided) && valueProvided.length === 0)) {
                    return;
                }
                this.__data.shape = valueProvided;
            }
        });

        /**
         * @description Where applicable, the color can be specified An appropriate controlled
    vocabulary shall be used The term and the term identifier shall be used.
         * @property {String[]|undefined}
        */
        Object.defineProperty(this, 'color', {
            // https://www.w3schools.com/js/js_object_es5.asp
            enumerable: true,
            configurable: true,
            get: () => this.__data.color,
            set: valueProvided => {
                if (valueProvided === undefined || valueProvided === null || (Array.isArray(valueProvided) && valueProvided.length === 0)) {
                    return;
                }
                this.__data.color = Array.isArray(valueProvided) ? valueProvided.map(v => v) : [valueProvided];
            }
        });

        /**
         * @description Where applicable, the imprint can be specified as text.
         * @property {String[]|undefined}
        */
        Object.defineProperty(this, 'imprint', {
            // https://www.w3schools.com/js/js_object_es5.asp
            enumerable: true,
            configurable: true,
            get: () => this.__data.imprint,
            set: valueProvided => {
                if (valueProvided === undefined || valueProvided === null || (Array.isArray(valueProvided) && valueProvided.length === 0)) {
                    return;
                }
                this.__data.imprint = Array.isArray(valueProvided) ? valueProvided.map(v => v) : [valueProvided];
            }
        });

        /**
         * @description Where applicable, the image can be provided The format of the image attachment
    shall be specified by regional implementations.
         * @property {Attachment[]|undefined}
        */
        Object.defineProperty(this, 'image', {
            // https://www.w3schools.com/js/js_object_es5.asp
            enumerable: true,
            configurable: true,
            get: () => this.__data.image,
            set: valueProvided => {
                if (valueProvided === undefined || valueProvided === null || (Array.isArray(valueProvided) && valueProvided.length === 0)) {
                    return;
                }
                let Attachment = require('../complex_types/attachment.js');
                this.__data.image = Array.isArray(valueProvided) ? valueProvided.map(v => new Attachment(v)) : [new Attachment(valueProvided)];
            }
        });

        /**
         * @description Where applicable, the scoring can be specified An appropriate controlled
    vocabulary shall be used The term and the term identifier shall be used.
         * @property {CodeableConcept|undefined}
        */
        Object.defineProperty(this, 'scoring', {
            // https://www.w3schools.com/js/js_object_es5.asp
            enumerable: true,
            configurable: true,
            get: () => this.__data.scoring,
            set: valueProvided => {
                if (valueProvided === undefined || valueProvided === null || (Array.isArray(valueProvided) && valueProvided.length === 0)) {
                    return;
                }
                let CodeableConcept = require('../complex_types/codeableConcept.js');
                this.__data.scoring = new CodeableConcept(valueProvided);
            }
        });


        /**
         * @description Specific instances of data or objects that have been accessed.
         * @property {AuditEventEntity[]|undefined}
         */
        Object.defineProperty(this, '_access', {
            // https://www.w3schools.com/js/js_object_es5.asp
            enumerable: true,
            configurable: true,
            get: () => this.__data._access,
            set: valueProvided => {
                if (valueProvided === undefined || valueProvided === null) {
                    return;
                }
                this.__data._access = valueProvided;
            }
        });

        // --- Now copy properties from passed in object ----
        Object.assign(this, {
            id,
            extension,
            modifierExtension,
            height,
            width,
            depth,
            weight,
            nominalVolume,
            externalDiameter,
            shape,
            color,
            imprint,
            image,
            scoring,
        });

    }



    /**
     * Returns JSON representation of entity
     * @return {Object}
     */
    toJSON() {
        const {removeNull} = require('../../../../utils/nullRemover');

        return removeNull({
            id: this.id,
            extension: this.extension && this.extension.map(v => v.toJSON()),
            modifierExtension: this.modifierExtension && this.modifierExtension.map(v => v.toJSON()),
            height: this.height && this.height.toJSON(),
            width: this.width && this.width.toJSON(),
            depth: this.depth && this.depth.toJSON(),
            weight: this.weight && this.weight.toJSON(),
            nominalVolume: this.nominalVolume && this.nominalVolume.toJSON(),
            externalDiameter: this.externalDiameter && this.externalDiameter.toJSON(),
            shape: this.shape,
            color: this.color,
            imprint: this.imprint,
            image: this.image && this.image.map(v => v.toJSON()),
            scoring: this.scoring && this.scoring.toJSON(),
        });
    }

    /**
     * Returns JSON representation of entity
     * @return {Object}
     */
    toJSONInternal() {
        const {removeNull} = require('../../../../utils/nullRemover');
        const json = this.toJSON();

        if (this._access) {
            json._access = this._access;
        }
        return removeNull(json);
    }
}

module.exports = ProdCharacteristic;
