/* eslint-disable no-unused-vars */
// This file is auto-generated by generate_classes so do not edit manually

/**
Questionnaire.Item
    A structured set of questions intended to guide the collection of answers from
    end-users. Questionnaires provide detailed control over order, presentation,
    phraseology and grouping to allow coherent, consistent data collection.
*/
class QuestionnaireItem {
    constructor(
        {
            id,
            extension,
            modifierExtension,
            linkId,
            definition,
            code,
            prefix,
            text,
            type,
            enableWhen,
            enableBehavior,
            required,
            repeats,
            readOnly,
            maxLength,
            answerValueSet,
            answerOption,
            initial,
            item,
        }
    ) {
        // Create an object to store all props
        Object.defineProperty(this, '__data', {
          value: {}
        }); // Define getters and setters as enumerable

        /**
         * @description None
         * @property {String|undefined}
        */
        Object.defineProperty(this, 'id', {
            enumerable: true,
            get: () => this.__data.id,
            set: valueProvided => {
                if (valueProvided === undefined || valueProvided === null) {
                    return;
                }
                this.__data.id = valueProvided;
            }
        });

        /**
         * @description May be used to represent additional information that is not part of the basic
    definition of the element. To make the use of extensions safe and manageable,
    there is a strict set of governance  applied to the definition and use of
    extensions. Though any implementer can define an extension, there is a set of
    requirements that SHALL be met as part of the definition of the extension.
         * @property {Extension[]|undefined}
        */
        Object.defineProperty(this, 'extension', {
            enumerable: true,
            get: () => this.__data.extension,
            set: valueProvided => {
                if (valueProvided === undefined || valueProvided === null) {
                    return;
                }
                let Extension = require('../extensions/extension.js');
                this.__data.extension = Array.isArray(valueProvided) ? valueProvided.map(v => new Extension(v)) : [new Extension(valueProvided)];
            }
        });

        /**
         * @description May be used to represent additional information that is not part of the basic
    definition of the element and that modifies the understanding of the element
    in which it is contained and/or the understanding of the containing element's
    descendants. Usually modifier elements provide negation or qualification. To
    make the use of extensions safe and manageable, there is a strict set of
    governance applied to the definition and use of extensions. Though any
    implementer can define an extension, there is a set of requirements that SHALL
    be met as part of the definition of the extension. Applications processing a
    resource are required to check for modifier extensions.

    Modifier extensions SHALL NOT change the meaning of any elements on Resource
    or DomainResource (including cannot change the meaning of modifierExtension
    itself).
         * @property {Extension[]|undefined}
        */
        Object.defineProperty(this, 'modifierExtension', {
            enumerable: true,
            get: () => this.__data.modifierExtension,
            set: valueProvided => {
                if (valueProvided === undefined || valueProvided === null) {
                    return;
                }
                let Extension = require('../extensions/extension.js');
                this.__data.modifierExtension = Array.isArray(valueProvided) ? valueProvided.map(v => new Extension(v)) : [new Extension(valueProvided)];
            }
        });

        /**
         * @description An identifier that is unique within the Questionnaire allowing linkage to the
    equivalent item in a QuestionnaireResponse resource.
         * @property {String}
        */
        Object.defineProperty(this, 'linkId', {
            enumerable: true,
            get: () => this.__data.linkId,
            set: valueProvided => {
                if (valueProvided === undefined || valueProvided === null) {
                    return;
                }
                this.__data.linkId = valueProvided;
            }
        });

        /**
         * @description This element is a URI that refers to an [[[ElementDefinition]]] that provides
    information about this item, including information that might otherwise be
    included in the instance of the Questionnaire resource. A detailed description
    of the construction of the URI is shown in Comments, below. If this element is
    present then the following element values MAY be derived from the Element
    Definition if the corresponding elements of this Questionnaire resource
    instance have no value:

    * code (ElementDefinition.code)
    * type (ElementDefinition.type)
    * required (ElementDefinition.min)
    * repeats (ElementDefinition.max)
    * maxLength (ElementDefinition.maxLength)
    * answerValueSet (ElementDefinition.binding)
    * options (ElementDefinition.binding).
         * @property {uri|undefined}
        */
        Object.defineProperty(this, 'definition', {
            enumerable: true,
            get: () => this.__data.definition,
            set: valueProvided => {
                if (valueProvided === undefined || valueProvided === null) {
                    return;
                }
                this.__data.definition = valueProvided;
            }
        });

        /**
         * @description A terminology code that corresponds to this group or question (e.g. a code
    from LOINC, which defines many questions and answers).
         * @property {Coding[]|undefined}
        */
        Object.defineProperty(this, 'code', {
            enumerable: true,
            get: () => this.__data.code,
            set: valueProvided => {
                if (valueProvided === undefined || valueProvided === null) {
                    return;
                }
                let Coding = require('../complex_types/coding.js');
                this.__data.code = Array.isArray(valueProvided) ? valueProvided.map(v => new Coding(v)) : [new Coding(valueProvided)];
            }
        });

        /**
         * @description A short label for a particular group, question or set of display text within
    the questionnaire used for reference by the individual completing the
    questionnaire.
         * @property {String|undefined}
        */
        Object.defineProperty(this, 'prefix', {
            enumerable: true,
            get: () => this.__data.prefix,
            set: valueProvided => {
                if (valueProvided === undefined || valueProvided === null) {
                    return;
                }
                this.__data.prefix = valueProvided;
            }
        });

        /**
         * @description The name of a section, the text of a question or text content for a display
    item.
         * @property {String|undefined}
        */
        Object.defineProperty(this, 'text', {
            enumerable: true,
            get: () => this.__data.text,
            set: valueProvided => {
                if (valueProvided === undefined || valueProvided === null) {
                    return;
                }
                this.__data.text = valueProvided;
            }
        });

        /**
         * @description The type of questionnaire item this is - whether text for display, a grouping
    of other items or a particular type of data to be captured (string, integer,
    coded choice, etc.).
         * @property {code}
        */
        Object.defineProperty(this, 'type', {
            enumerable: true,
            get: () => this.__data.type,
            set: valueProvided => {
                if (valueProvided === undefined || valueProvided === null) {
                    return;
                }
                this.__data.type = valueProvided;
            }
        });

        /**
         * @description A constraint indicating that this item should only be enabled (displayed/allow
    answers to be captured) when the specified condition is true.
         * @property {QuestionnaireEnableWhen[]|undefined}
        */
        Object.defineProperty(this, 'enableWhen', {
            enumerable: true,
            get: () => this.__data.enableWhen,
            set: valueProvided => {
                if (valueProvided === undefined || valueProvided === null) {
                    return;
                }
                let QuestionnaireEnableWhen = require('../backbone_elements/questionnaireEnableWhen.js');
                this.__data.enableWhen = Array.isArray(valueProvided) ? valueProvided.map(v => new QuestionnaireEnableWhen(v)) : [new QuestionnaireEnableWhen(valueProvided)];
            }
        });

        /**
         * @description Controls how multiple enableWhen values are interpreted -  whether all or any
    must be true.
         * @property {code|undefined}
        */
        Object.defineProperty(this, 'enableBehavior', {
            enumerable: true,
            get: () => this.__data.enableBehavior,
            set: valueProvided => {
                if (valueProvided === undefined || valueProvided === null) {
                    return;
                }
                this.__data.enableBehavior = valueProvided;
            }
        });

        /**
         * @description An indication, if true, that the item must be present in a "completed"
    QuestionnaireResponse.  If false, the item may be skipped when answering the
    questionnaire.
         * @property {Boolean|undefined}
        */
        Object.defineProperty(this, 'required', {
            enumerable: true,
            get: () => this.__data.required,
            set: valueProvided => {
                if (valueProvided === undefined || valueProvided === null) {
                    return;
                }
                this.__data.required = valueProvided;
            }
        });

        /**
         * @description An indication, if true, that the item may occur multiple times in the
    response, collecting multiple answers for questions or multiple sets of
    answers for groups.
         * @property {Boolean|undefined}
        */
        Object.defineProperty(this, 'repeats', {
            enumerable: true,
            get: () => this.__data.repeats,
            set: valueProvided => {
                if (valueProvided === undefined || valueProvided === null) {
                    return;
                }
                this.__data.repeats = valueProvided;
            }
        });

        /**
         * @description An indication, when true, that the value cannot be changed by a human
    respondent to the Questionnaire.
         * @property {Boolean|undefined}
        */
        Object.defineProperty(this, 'readOnly', {
            enumerable: true,
            get: () => this.__data.readOnly,
            set: valueProvided => {
                if (valueProvided === undefined || valueProvided === null) {
                    return;
                }
                this.__data.readOnly = valueProvided;
            }
        });

        /**
         * @description The maximum number of characters that are permitted in the answer to be
    considered a "valid" QuestionnaireResponse.
         * @property {Int|undefined}
        */
        Object.defineProperty(this, 'maxLength', {
            enumerable: true,
            get: () => this.__data.maxLength,
            set: valueProvided => {
                if (valueProvided === undefined || valueProvided === null) {
                    return;
                }
                this.__data.maxLength = valueProvided;
            }
        });

        /**
         * @description A reference to a value set containing a list of codes representing permitted
    answers for a "choice" or "open-choice" question.
         * @property {canonical|undefined}
        */
        Object.defineProperty(this, 'answerValueSet', {
            enumerable: true,
            get: () => this.__data.answerValueSet,
            set: valueProvided => {
                if (valueProvided === undefined || valueProvided === null) {
                    return;
                }
                this.__data.answerValueSet = valueProvided;
            }
        });

        /**
         * @description One of the permitted answers for a "choice" or "open-choice" question.
         * @property {QuestionnaireAnswerOption[]|undefined}
        */
        Object.defineProperty(this, 'answerOption', {
            enumerable: true,
            get: () => this.__data.answerOption,
            set: valueProvided => {
                if (valueProvided === undefined || valueProvided === null) {
                    return;
                }
                let QuestionnaireAnswerOption = require('../backbone_elements/questionnaireAnswerOption.js');
                this.__data.answerOption = Array.isArray(valueProvided) ? valueProvided.map(v => new QuestionnaireAnswerOption(v)) : [new QuestionnaireAnswerOption(valueProvided)];
            }
        });

        /**
         * @description One or more values that should be pre-populated in the answer when initially
    rendering the questionnaire for user input.
         * @property {QuestionnaireInitial[]|undefined}
        */
        Object.defineProperty(this, 'initial', {
            enumerable: true,
            get: () => this.__data.initial,
            set: valueProvided => {
                if (valueProvided === undefined || valueProvided === null) {
                    return;
                }
                let QuestionnaireInitial = require('../backbone_elements/questionnaireInitial.js');
                this.__data.initial = Array.isArray(valueProvided) ? valueProvided.map(v => new QuestionnaireInitial(v)) : [new QuestionnaireInitial(valueProvided)];
            }
        });

        /**
         * @description Text, questions and other groups to be nested beneath a question or group.
         * @property {QuestionnaireItem[]|undefined}
        */
        Object.defineProperty(this, 'item', {
            enumerable: true,
            get: () => this.__data.item,
            set: valueProvided => {
                if (valueProvided === undefined || valueProvided === null) {
                    return;
                }
                this.__data.item = Array.isArray(valueProvided) ? valueProvided.map(v => new QuestionnaireItem(v)) : [new QuestionnaireItem(valueProvided)];
            }
        });

        Object.assign(this, {
            id,
            extension,
            modifierExtension,
            linkId,
            definition,
            code,
            prefix,
            text,
            type,
            enableWhen,
            enableBehavior,
            required,
            repeats,
            readOnly,
            maxLength,
            answerValueSet,
            answerOption,
            initial,
            item,
        });

        // Define a default non-writable resourceType property

        Object.defineProperty(this, 'resourceType', {
            value: 'QuestionnaireItem',
            enumerable: true,
            writable: false
        });
    }

    static get resourceType() {
        return 'QuestionnaireItem';
    }

    toJSON() {
        return {
            id: this.id,
            extension: this.extension && this.extension.map(v => v.toJSON()),
            modifierExtension: this.modifierExtension && this.modifierExtension.map(v => v.toJSON()),
            linkId: this.linkId,
            definition: this.definition,
            code: this.code && this.code.map(v => v.toJSON()),
            prefix: this.prefix,
            text: this.text,
            type: this.type,
            enableWhen: this.enableWhen && this.enableWhen.map(v => v.toJSON()),
            enableBehavior: this.enableBehavior,
            required: this.required,
            repeats: this.repeats,
            readOnly: this.readOnly,
            maxLength: this.maxLength,
            answerValueSet: this.answerValueSet,
            answerOption: this.answerOption && this.answerOption.map(v => v.toJSON()),
            initial: this.initial && this.initial.map(v => v.toJSON()),
            item: this.item && this.item.map(v => v.toJSON()),
        };
    }
}

module.exports = QuestionnaireItem;
