// This file is auto-generated by generate_serializers so do not edit manually
const BaseSerializer = require('../customSerializers/baseSerializer.js');

/** @type {import('../complexTypes/extension.js')} */
let ExtensionSerializer;
/** @type {import('../complexTypes/codeableConcept.js')} */
let CodeableConceptSerializer;
/** @type {import('../complexTypes/quantity.js')} */
let QuantitySerializer;
/** @type {import('../complexTypes/money.js')} */
let MoneySerializer;
/** @type {import('../backboneElements/coverageException.js')} */
let CoverageExceptionSerializer;

class CoverageCostToBeneficiarySerializer extends BaseSerializer {
    // Private cache for lazy-loaded property configs
    #configCache = {};

    fhirPropertyToSerializerMap = {
        id: null,
        extension: () => {
            if (!this.#configCache['extension']) {
                if (!ExtensionSerializer) {
                    ExtensionSerializer = require('../complexTypes/extension.js');
                }
                this.#configCache['extension'] = {
                    serializeFunction: 'serializeArray',
                    serializerClass: ExtensionSerializer
                };
            }
            return this.#configCache['extension'];
        },
        modifierExtension: () => {
            if (!this.#configCache['modifierExtension']) {
                if (!ExtensionSerializer) {
                    ExtensionSerializer = require('../complexTypes/extension.js');
                }
                this.#configCache['modifierExtension'] = {
                    serializeFunction: 'serializeArray',
                    serializerClass: ExtensionSerializer
                };
            }
            return this.#configCache['modifierExtension'];
        },
        type: () => {
            if (!this.#configCache['type']) {
                if (!CodeableConceptSerializer) {
                    CodeableConceptSerializer = require('../complexTypes/codeableConcept.js');
                }
                this.#configCache['type'] = {
                    serializeFunction: 'serialize',
                    serializerClass: CodeableConceptSerializer
                };
            }
            return this.#configCache['type'];
        },
        valueQuantity: () => {
            if (!this.#configCache['valueQuantity']) {
                if (!QuantitySerializer) {
                    QuantitySerializer = require('../complexTypes/quantity.js');
                }
                this.#configCache['valueQuantity'] = {
                    serializeFunction: 'serialize',
                    serializerClass: QuantitySerializer
                };
            }
            return this.#configCache['valueQuantity'];
        },
        valueMoney: () => {
            if (!this.#configCache['valueMoney']) {
                if (!MoneySerializer) {
                    MoneySerializer = require('../complexTypes/money.js');
                }
                this.#configCache['valueMoney'] = {
                    serializeFunction: 'serialize',
                    serializerClass: MoneySerializer
                };
            }
            return this.#configCache['valueMoney'];
        },
        exception: () => {
            if (!this.#configCache['exception']) {
                if (!CoverageExceptionSerializer) {
                    CoverageExceptionSerializer = require('../backboneElements/coverageException.js');
                }
                this.#configCache['exception'] = {
                    serializeFunction: 'serializeArray',
                    serializerClass: CoverageExceptionSerializer
                };
            }
            return this.#configCache['exception'];
        }
    };

    allPropertyToSerializerMap = this.fhirPropertyToSerializerMap;
}

module.exports = new CoverageCostToBeneficiarySerializer();
