// This file is auto-generated by generate_serializers so do not edit manually
const BaseSerializer = require('../customSerializers/baseSerializer.js');

/** @type {import('../complexTypes/extension.js')} */
let ExtensionSerializer;
/** @type {import('../backboneElements/exampleScenarioContainedInstance.js')} */
let ExampleScenarioContainedInstanceSerializer;

class ExampleScenarioOperationSerializer extends BaseSerializer {
    // Private cache for lazy-loaded property configs
    #configCache = {};

    fhirPropertyToSerializerMap = {
        id: null,
        extension: () => {
            if (!this.#configCache['extension']) {
                if (!ExtensionSerializer) {
                    ExtensionSerializer = require('../complexTypes/extension.js');
                }
                this.#configCache['extension'] = {
                    serializeFunction: 'serializeArray',
                    serializerClass: ExtensionSerializer
                };
            }
            return this.#configCache['extension'];
        },
        modifierExtension: () => {
            if (!this.#configCache['modifierExtension']) {
                if (!ExtensionSerializer) {
                    ExtensionSerializer = require('../complexTypes/extension.js');
                }
                this.#configCache['modifierExtension'] = {
                    serializeFunction: 'serializeArray',
                    serializerClass: ExtensionSerializer
                };
            }
            return this.#configCache['modifierExtension'];
        },
        number: null,
        type: null,
        name: null,
        initiator: null,
        receiver: null,
        description: null,
        initiatorActive: null,
        receiverActive: null,
        request: () => {
            if (!this.#configCache['request']) {
                if (!ExampleScenarioContainedInstanceSerializer) {
                    ExampleScenarioContainedInstanceSerializer = require('../backboneElements/exampleScenarioContainedInstance.js');
                }
                this.#configCache['request'] = {
                    serializeFunction: 'serialize',
                    serializerClass: ExampleScenarioContainedInstanceSerializer
                };
            }
            return this.#configCache['request'];
        },
        response: () => {
            if (!this.#configCache['response']) {
                if (!ExampleScenarioContainedInstanceSerializer) {
                    ExampleScenarioContainedInstanceSerializer = require('../backboneElements/exampleScenarioContainedInstance.js');
                }
                this.#configCache['response'] = {
                    serializeFunction: 'serialize',
                    serializerClass: ExampleScenarioContainedInstanceSerializer
                };
            }
            return this.#configCache['response'];
        }
    };

    allPropertyToSerializerMap = this.fhirPropertyToSerializerMap;
}

module.exports = new ExampleScenarioOperationSerializer();
