// This file is auto-generated by generate_serializers so do not edit manually
const BaseSerializer = require('../customSerializers/baseSerializer.js');

/** @type {import('../complexTypes/extension.js')} */
let ExtensionSerializer;
/** @type {import('../complexTypes/codeableConcept.js')} */
let CodeableConceptSerializer;
/** @type {import('../complexTypes/reference.js')} */
let ReferenceSerializer;

class MedicinalProductDefinitionContactSerializer extends BaseSerializer {
    // Private cache for lazy-loaded property configs
    #configCache = {};

    fhirPropertyToSerializerMap = {
        id: null,
        extension: () => {
            if (!this.#configCache['extension']) {
                if (!ExtensionSerializer) {
                    ExtensionSerializer = require('../complexTypes/extension.js');
                }
                this.#configCache['extension'] = {
                    serializeFunction: 'serializeArray',
                    serializerClass: ExtensionSerializer
                };
            }
            return this.#configCache['extension'];
        },
        modifierExtension: () => {
            if (!this.#configCache['modifierExtension']) {
                if (!ExtensionSerializer) {
                    ExtensionSerializer = require('../complexTypes/extension.js');
                }
                this.#configCache['modifierExtension'] = {
                    serializeFunction: 'serializeArray',
                    serializerClass: ExtensionSerializer
                };
            }
            return this.#configCache['modifierExtension'];
        },
        type: () => {
            if (!this.#configCache['type']) {
                if (!CodeableConceptSerializer) {
                    CodeableConceptSerializer = require('../complexTypes/codeableConcept.js');
                }
                this.#configCache['type'] = {
                    serializeFunction: 'serialize',
                    serializerClass: CodeableConceptSerializer
                };
            }
            return this.#configCache['type'];
        },
        contact: () => {
            if (!this.#configCache['contact']) {
                if (!ReferenceSerializer) {
                    ReferenceSerializer = require('../complexTypes/reference.js');
                }
                this.#configCache['contact'] = {
                    serializeFunction: 'serialize',
                    serializerClass: ReferenceSerializer
                };
            }
            return this.#configCache['contact'];
        }
    };

    allPropertyToSerializerMap = this.fhirPropertyToSerializerMap;
}

module.exports = new MedicinalProductDefinitionContactSerializer();
