// This file is auto-generated by generate_serializers so do not edit manually
const BaseSerializer = require('../customSerializers/baseSerializer.js');

/** @type {import('../complexTypes/extension.js')} */
let ExtensionSerializer;
/** @type {import('../complexTypes/codeableConcept.js')} */
let CodeableConceptSerializer;
/** @type {import('../complexTypes/quantity.js')} */
let QuantitySerializer;
/** @type {import('../complexTypes/ratio.js')} */
let RatioSerializer;

class MedicationAdministrationDosageSerializer extends BaseSerializer {
    // Private cache for lazy-loaded property configs
    #configCache = {};

    fhirPropertyToSerializerMap = {
        id: null,
        extension: () => {
            // Lazy load serializer only when first accessed (with caching)
            if (!this.#configCache['extension']) {
                if (!ExtensionSerializer) {
                    ExtensionSerializer = require('../complexTypes/extension.js');
                }
                this.#configCache['extension'] = {
                    serializeFunction: 'serializeArray',
                    serializerClass: ExtensionSerializer
                };
            }
            return this.#configCache['extension'];
        },
        modifierExtension: () => {
            // Lazy load serializer only when first accessed (with caching)
            if (!this.#configCache['modifierExtension']) {
                if (!ExtensionSerializer) {
                    ExtensionSerializer = require('../complexTypes/extension.js');
                }
                this.#configCache['modifierExtension'] = {
                    serializeFunction: 'serializeArray',
                    serializerClass: ExtensionSerializer
                };
            }
            return this.#configCache['modifierExtension'];
        },
        text: null,
        site: () => {
            // Lazy load serializer only when first accessed (with caching)
            if (!this.#configCache['site']) {
                if (!CodeableConceptSerializer) {
                    CodeableConceptSerializer = require('../complexTypes/codeableConcept.js');
                }
                this.#configCache['site'] = {
                    serializeFunction: 'serialize',
                    serializerClass: CodeableConceptSerializer
                };
            }
            return this.#configCache['site'];
        },
        route: () => {
            // Lazy load serializer only when first accessed (with caching)
            if (!this.#configCache['route']) {
                if (!CodeableConceptSerializer) {
                    CodeableConceptSerializer = require('../complexTypes/codeableConcept.js');
                }
                this.#configCache['route'] = {
                    serializeFunction: 'serialize',
                    serializerClass: CodeableConceptSerializer
                };
            }
            return this.#configCache['route'];
        },
        method: () => {
            // Lazy load serializer only when first accessed (with caching)
            if (!this.#configCache['method']) {
                if (!CodeableConceptSerializer) {
                    CodeableConceptSerializer = require('../complexTypes/codeableConcept.js');
                }
                this.#configCache['method'] = {
                    serializeFunction: 'serialize',
                    serializerClass: CodeableConceptSerializer
                };
            }
            return this.#configCache['method'];
        },
        dose: () => {
            // Lazy load serializer only when first accessed (with caching)
            if (!this.#configCache['dose']) {
                if (!QuantitySerializer) {
                    QuantitySerializer = require('../complexTypes/quantity.js');
                }
                this.#configCache['dose'] = {
                    serializeFunction: 'serialize',
                    serializerClass: QuantitySerializer
                };
            }
            return this.#configCache['dose'];
        },
        rateRatio: () => {
            // Lazy load serializer only when first accessed (with caching)
            if (!this.#configCache['rateRatio']) {
                if (!RatioSerializer) {
                    RatioSerializer = require('../complexTypes/ratio.js');
                }
                this.#configCache['rateRatio'] = {
                    serializeFunction: 'serialize',
                    serializerClass: RatioSerializer
                };
            }
            return this.#configCache['rateRatio'];
        },
        rateQuantity: () => {
            // Lazy load serializer only when first accessed (with caching)
            if (!this.#configCache['rateQuantity']) {
                if (!QuantitySerializer) {
                    QuantitySerializer = require('../complexTypes/quantity.js');
                }
                this.#configCache['rateQuantity'] = {
                    serializeFunction: 'serialize',
                    serializerClass: QuantitySerializer
                };
            }
            return this.#configCache['rateQuantity'];
        }
    };

    allPropertyToSerializerMap = this.fhirPropertyToSerializerMap;
}

module.exports = new MedicationAdministrationDosageSerializer();
