// This file is auto-generated by generate_serializers so do not edit manually
const BaseSerializer = require('../customSerializers/baseSerializer.js');

/** @type {import('../complexTypes/extension.js')} */
let ExtensionSerializer;
/** @type {import('../complexTypes/expression.js')} */
let ExpressionSerializer;

class PlanDefinitionDynamicValueSerializer extends BaseSerializer {
    // Private cache for lazy-loaded property configs
    #configCache = {};

    fhirPropertyToSerializerMap = {
        id: null,
        extension: () => {
            // Lazy load serializer only when first accessed (with caching)
            if (!this.#configCache['extension']) {
                if (!ExtensionSerializer) {
                    ExtensionSerializer = require('../complexTypes/extension.js');
                }
                this.#configCache['extension'] = {
                    serializeFunction: 'serializeArray',
                    serializerClass: ExtensionSerializer
                };
            }
            return this.#configCache['extension'];
        },
        modifierExtension: () => {
            // Lazy load serializer only when first accessed (with caching)
            if (!this.#configCache['modifierExtension']) {
                if (!ExtensionSerializer) {
                    ExtensionSerializer = require('../complexTypes/extension.js');
                }
                this.#configCache['modifierExtension'] = {
                    serializeFunction: 'serializeArray',
                    serializerClass: ExtensionSerializer
                };
            }
            return this.#configCache['modifierExtension'];
        },
        path: null,
        expression: () => {
            // Lazy load serializer only when first accessed (with caching)
            if (!this.#configCache['expression']) {
                if (!ExpressionSerializer) {
                    ExpressionSerializer = require('../complexTypes/expression.js');
                }
                this.#configCache['expression'] = {
                    serializeFunction: 'serialize',
                    serializerClass: ExpressionSerializer
                };
            }
            return this.#configCache['expression'];
        }
    };

    allPropertyToSerializerMap = this.fhirPropertyToSerializerMap;
}

module.exports = new PlanDefinitionDynamicValueSerializer();
