// This file is auto-generated by generate_serializers so do not edit manually
const BaseSerializer = require('../customSerializers/baseSerializer.js');

/** @type {import('../complexTypes/extension.js')} */
let ExtensionSerializer;
/** @type {import('../complexTypes/coding.js')} */
let CodingSerializer;

class TestScriptOriginSerializer extends BaseSerializer {
    // Private cache for lazy-loaded property configs
    #configCache = {};

    fhirPropertyToSerializerMap = {
        id: null,
        extension: () => {
            // Lazy load serializer only when first accessed (with caching)
            if (!this.#configCache['extension']) {
                if (!ExtensionSerializer) {
                    ExtensionSerializer = require('../complexTypes/extension.js');
                }
                this.#configCache['extension'] = {
                    serializeFunction: 'serializeArray',
                    serializerClass: ExtensionSerializer
                };
            }
            return this.#configCache['extension'];
        },
        modifierExtension: () => {
            // Lazy load serializer only when first accessed (with caching)
            if (!this.#configCache['modifierExtension']) {
                if (!ExtensionSerializer) {
                    ExtensionSerializer = require('../complexTypes/extension.js');
                }
                this.#configCache['modifierExtension'] = {
                    serializeFunction: 'serializeArray',
                    serializerClass: ExtensionSerializer
                };
            }
            return this.#configCache['modifierExtension'];
        },
        index: null,
        profile: () => {
            // Lazy load serializer only when first accessed (with caching)
            if (!this.#configCache['profile']) {
                if (!CodingSerializer) {
                    CodingSerializer = require('../complexTypes/coding.js');
                }
                this.#configCache['profile'] = {
                    serializeFunction: 'serialize',
                    serializerClass: CodingSerializer
                };
            }
            return this.#configCache['profile'];
        }
    };

    allPropertyToSerializerMap = this.fhirPropertyToSerializerMap;
}

module.exports = new TestScriptOriginSerializer();
