// This file is auto-generated by generate_classes so do not edit manually

/** @type {import('../complex_types/extension.js')} */
let ExtensionSerializer;
/** @type {import('../complex_types/coding.js')} */
let CodingSerializer;
/** @type {import('../complex_types/reference.js')} */
let ReferenceSerializer;
/** @type {import('../backbone_elements/imagingStudyPerformer.js')} */
let ImagingStudyPerformerSerializer;
/** @type {import('../backbone_elements/imagingStudyInstance.js')} */
let ImagingStudyInstanceSerializer;

/**
 * Lazy loads the required serializers
 * It esnures that require is called only once for each serializer to minimize the call stack for require()
 * @returns {any}
 */
function initializeSerializers(serializerName) {
    initializeResourceSerializer()
    if (serializerName === 'Extension' && !ExtensionSerializer) {
        ExtensionSerializer = require('../complex_types/extension.js');
        return ExtensionSerializer;
    }
    if (serializerName === 'Coding' && !CodingSerializer) {
        CodingSerializer = require('../complex_types/coding.js');
        return CodingSerializer;
    }
    if (serializerName === 'Reference' && !ReferenceSerializer) {
        ReferenceSerializer = require('../complex_types/reference.js');
        return ReferenceSerializer;
    }
    if (serializerName === 'ImagingStudyPerformer' && !ImagingStudyPerformerSerializer) {
        ImagingStudyPerformerSerializer = require('../backbone_elements/imagingStudyPerformer.js');
        return ImagingStudyPerformerSerializer;
    }
    if (serializerName === 'ImagingStudyInstance' && !ImagingStudyInstanceSerializer) {
        ImagingStudyInstanceSerializer = require('../backbone_elements/imagingStudyInstance.js');
        return ImagingStudyInstanceSerializer;
    }
}

/** @type {import('../../../fhirResourceSerializer.js').FhirResourceSerializer} */
let FhirResourceSerializer;

function initializeResourceSerializer() {
    if (!FhirResourceSerializer) {
        FhirResourceSerializer = require('../../../fhirResourceSerializer.js').FhirResourceSerializer;
    }

    return FhirResourceSerializer;
}

class ImagingStudySeriesSerializer {
    static propertyToSerializerMap = {
        id: null,
        extension: (value, context) => {
            initializeSerializers('Extension');
            return FhirResourceSerializer.serializeArray(value, ExtensionSerializer, context);
        },
        modifierExtension: (value, context) => {
            initializeSerializers('Extension');
            return FhirResourceSerializer.serializeArray(value, ExtensionSerializer, context);
        },
        uid: null,
        number: null,
        modality: (value, context) => {
            initializeSerializers('Coding');
            return FhirResourceSerializer.serialize(value, CodingSerializer, context);
        },
        description: null,
        numberOfInstances: null,
        endpoint: (value, context) => {
            initializeSerializers('Reference');
            return FhirResourceSerializer.serializeArray(value, ReferenceSerializer, context);
        },
        bodySite: (value, context) => {
            initializeSerializers('Coding');
            return FhirResourceSerializer.serialize(value, CodingSerializer, context);
        },
        laterality: (value, context) => {
            initializeSerializers('Coding');
            return FhirResourceSerializer.serialize(value, CodingSerializer, context);
        },
        specimen: (value, context) => {
            initializeSerializers('Reference');
            return FhirResourceSerializer.serializeArray(value, ReferenceSerializer, context);
        },
        started: null,
        performer: (value, context) => {
            initializeSerializers('ImagingStudyPerformer');
            return FhirResourceSerializer.serializeArray(value, ImagingStudyPerformerSerializer, context);
        },
        instance: (value, context) => {
            initializeSerializers('ImagingStudyInstance');
            return FhirResourceSerializer.serializeArray(value, ImagingStudyInstanceSerializer, context);
        }
    };

    /**
     * This methods cleans the raw json by removing additional fields which are not defined
     * according to FHIR Specs
     * @param {any} rawJson
     * @param {Object} context
     * @returns {any} Cleaned object
     */
    static serialize(rawJson, context = {}) {
        if (!rawJson) return rawJson;

        // Handle array case
        if (Array.isArray(rawJson)) {
            return rawJson.map(item => ImagingStudySeriesSerializer.serialize(item, context));
        }

        // Handle non-object case
        if (typeof rawJson !== 'object') return rawJson;

        Object.keys(rawJson).forEach(propertyName => {
            const value = rawJson[propertyName];

            if (value === null || value === undefined) {
                delete rawJson[propertyName];
                return;
            }

            if (propertyName in ImagingStudySeriesSerializer.propertyToSerializerMap) {
                if (ImagingStudySeriesSerializer.propertyToSerializerMap[propertyName]) {
                    const serializedValue = ImagingStudySeriesSerializer.propertyToSerializerMap[propertyName](value, context);
                    if (serializedValue === null || serializedValue === undefined) {
                        delete rawJson[propertyName];
                    } else {
                        rawJson[propertyName] = serializedValue;
                    }
                }
            } else {
                delete rawJson[propertyName];
            }
        });

        return rawJson;
    }
}

module.exports = ImagingStudySeriesSerializer;
