// This file is auto-generated by generate_classes so do not edit manually

/** @type {import('../complex_types/extension.js')} */
let ExtensionSerializer;
/** @type {import('../backbone_elements/medicationKnowledgeDosage.js')} */
let MedicationKnowledgeDosageSerializer;
/** @type {import('../complex_types/codeableConcept.js')} */
let CodeableConceptSerializer;
/** @type {import('../complex_types/reference.js')} */
let ReferenceSerializer;
/** @type {import('../backbone_elements/medicationKnowledgePatientCharacteristics.js')} */
let MedicationKnowledgePatientCharacteristicsSerializer;

/**
 * Lazy loads the required serializers
 * It esnures that require is called only once for each serializer to minimize the call stack for require()
 * @returns {any}
 */
function initializeSerializers(serializerName) {
    initializeResourceSerializer()
    if (serializerName === 'Extension' && !ExtensionSerializer) {
        ExtensionSerializer = require('../complex_types/extension.js');
        return ExtensionSerializer;
    }
    if (serializerName === 'MedicationKnowledgeDosage' && !MedicationKnowledgeDosageSerializer) {
        MedicationKnowledgeDosageSerializer = require('../backbone_elements/medicationKnowledgeDosage.js');
        return MedicationKnowledgeDosageSerializer;
    }
    if (serializerName === 'CodeableConcept' && !CodeableConceptSerializer) {
        CodeableConceptSerializer = require('../complex_types/codeableConcept.js');
        return CodeableConceptSerializer;
    }
    if (serializerName === 'Reference' && !ReferenceSerializer) {
        ReferenceSerializer = require('../complex_types/reference.js');
        return ReferenceSerializer;
    }
    if (serializerName === 'MedicationKnowledgePatientCharacteristics' && !MedicationKnowledgePatientCharacteristicsSerializer) {
        MedicationKnowledgePatientCharacteristicsSerializer = require('../backbone_elements/medicationKnowledgePatientCharacteristics.js');
        return MedicationKnowledgePatientCharacteristicsSerializer;
    }
}

/** @type {import('../../../fhirResourceSerializer.js').FhirResourceSerializer} */
let FhirResourceSerializer;

function initializeResourceSerializer() {
    if (!FhirResourceSerializer) {
        FhirResourceSerializer = require('../../../fhirResourceSerializer.js').FhirResourceSerializer;
    }

    return FhirResourceSerializer;
}

class MedicationKnowledgeAdministrationGuidelinesSerializer {
    static propertyToSerializerMap = {
        id: null,
        extension: (value, context) => {
            initializeSerializers('Extension');
            return FhirResourceSerializer.serializeArray(value, ExtensionSerializer, context);
        },
        modifierExtension: (value, context) => {
            initializeSerializers('Extension');
            return FhirResourceSerializer.serializeArray(value, ExtensionSerializer, context);
        },
        dosage: (value, context) => {
            initializeSerializers('MedicationKnowledgeDosage');
            return FhirResourceSerializer.serializeArray(value, MedicationKnowledgeDosageSerializer, context);
        },
        indicationCodeableConcept: (value, context) => {
            initializeSerializers('CodeableConcept');
            return FhirResourceSerializer.serialize(value, CodeableConceptSerializer, context);
        },
        indicationReference: (value, context) => {
            initializeSerializers('Reference');
            return FhirResourceSerializer.serialize(value, ReferenceSerializer, context);
        },
        patientCharacteristics: (value, context) => {
            initializeSerializers('MedicationKnowledgePatientCharacteristics');
            return FhirResourceSerializer.serializeArray(value, MedicationKnowledgePatientCharacteristicsSerializer, context);
        }
    };

    /**
     * This methods cleans the raw json by removing additional fields which are not defined
     * according to FHIR Specs
     * @param {any} rawJson
     * @param {Object} context
     * @returns {any} Cleaned object
     */
    static serialize(rawJson, context = {}) {
        if (!rawJson) return rawJson;

        // Handle array case
        if (Array.isArray(rawJson)) {
            return rawJson.map(item => MedicationKnowledgeAdministrationGuidelinesSerializer.serialize(item, context));
        }

        // Handle non-object case
        if (typeof rawJson !== 'object') return rawJson;

        Object.keys(rawJson).forEach(propertyName => {
            const value = rawJson[propertyName];

            if (value === null || value === undefined) {
                delete rawJson[propertyName];
                return;
            }

            if (propertyName in MedicationKnowledgeAdministrationGuidelinesSerializer.propertyToSerializerMap) {
                if (MedicationKnowledgeAdministrationGuidelinesSerializer.propertyToSerializerMap[propertyName]) {
                    const serializedValue = MedicationKnowledgeAdministrationGuidelinesSerializer.propertyToSerializerMap[propertyName](value, context);
                    if (serializedValue === null || serializedValue === undefined) {
                        delete rawJson[propertyName];
                    } else {
                        rawJson[propertyName] = serializedValue;
                    }
                }
            } else {
                delete rawJson[propertyName];
            }
        });

        return rawJson;
    }
}

module.exports = MedicationKnowledgeAdministrationGuidelinesSerializer;
