// This file is auto-generated by generate_classes so do not edit manually

/** @type {import('../complex_types/extension.js')} */
let ExtensionSerializer;
/** @type {import('../complex_types/codeableConcept.js')} */
let CodeableConceptSerializer;
/** @type {import('../complex_types/relatedArtifact.js')} */
let RelatedArtifactSerializer;
/** @type {import('../backbone_elements/requestGroupCondition.js')} */
let RequestGroupConditionSerializer;
/** @type {import('../backbone_elements/requestGroupRelatedAction.js')} */
let RequestGroupRelatedActionSerializer;
/** @type {import('../complex_types/quantity.js')} */
let QuantitySerializer;
/** @type {import('../complex_types/period.js')} */
let PeriodSerializer;
/** @type {import('../complex_types/range.js')} */
let RangeSerializer;
/** @type {import('../backbone_elements/timing.js')} */
let TimingSerializer;
/** @type {import('../complex_types/reference.js')} */
let ReferenceSerializer;

/**
 * Lazy loads the required serializers
 * It esnures that require is called only once for each serializer to minimize the call stack for require()
 * @returns {any}
 */
function initializeSerializers(serializerName) {
    initializeResourceSerializer()
    if (serializerName === 'Extension' && !ExtensionSerializer) {
        ExtensionSerializer = require('../complex_types/extension.js');
        return ExtensionSerializer;
    }
    if (serializerName === 'CodeableConcept' && !CodeableConceptSerializer) {
        CodeableConceptSerializer = require('../complex_types/codeableConcept.js');
        return CodeableConceptSerializer;
    }
    if (serializerName === 'RelatedArtifact' && !RelatedArtifactSerializer) {
        RelatedArtifactSerializer = require('../complex_types/relatedArtifact.js');
        return RelatedArtifactSerializer;
    }
    if (serializerName === 'RequestGroupCondition' && !RequestGroupConditionSerializer) {
        RequestGroupConditionSerializer = require('../backbone_elements/requestGroupCondition.js');
        return RequestGroupConditionSerializer;
    }
    if (serializerName === 'RequestGroupRelatedAction' && !RequestGroupRelatedActionSerializer) {
        RequestGroupRelatedActionSerializer = require('../backbone_elements/requestGroupRelatedAction.js');
        return RequestGroupRelatedActionSerializer;
    }
    if (serializerName === 'Quantity' && !QuantitySerializer) {
        QuantitySerializer = require('../complex_types/quantity.js');
        return QuantitySerializer;
    }
    if (serializerName === 'Period' && !PeriodSerializer) {
        PeriodSerializer = require('../complex_types/period.js');
        return PeriodSerializer;
    }
    if (serializerName === 'Range' && !RangeSerializer) {
        RangeSerializer = require('../complex_types/range.js');
        return RangeSerializer;
    }
    if (serializerName === 'Timing' && !TimingSerializer) {
        TimingSerializer = require('../backbone_elements/timing.js');
        return TimingSerializer;
    }
    if (serializerName === 'Reference' && !ReferenceSerializer) {
        ReferenceSerializer = require('../complex_types/reference.js');
        return ReferenceSerializer;
    }
}

/** @type {import('../../../fhirResourceSerializer.js').FhirResourceSerializer} */
let FhirResourceSerializer;

function initializeResourceSerializer() {
    if (!FhirResourceSerializer) {
        FhirResourceSerializer = require('../../../fhirResourceSerializer.js').FhirResourceSerializer;
    }

    return FhirResourceSerializer;
}

class RequestGroupActionSerializer {
    static propertyToSerializerMap = {
        id: null,
        extension: (value, context) => {
            initializeSerializers('Extension');
            return FhirResourceSerializer.serializeArray(value, ExtensionSerializer, context);
        },
        modifierExtension: (value, context) => {
            initializeSerializers('Extension');
            return FhirResourceSerializer.serializeArray(value, ExtensionSerializer, context);
        },
        prefix: null,
        title: null,
        description: null,
        textEquivalent: null,
        priority: null,
        code: (value, context) => {
            initializeSerializers('CodeableConcept');
            return FhirResourceSerializer.serializeArray(value, CodeableConceptSerializer, context);
        },
        documentation: (value, context) => {
            initializeSerializers('RelatedArtifact');
            return FhirResourceSerializer.serializeArray(value, RelatedArtifactSerializer, context);
        },
        condition: (value, context) => {
            initializeSerializers('RequestGroupCondition');
            return FhirResourceSerializer.serializeArray(value, RequestGroupConditionSerializer, context);
        },
        relatedAction: (value, context) => {
            initializeSerializers('RequestGroupRelatedAction');
            return FhirResourceSerializer.serializeArray(value, RequestGroupRelatedActionSerializer, context);
        },
        timingDateTime: null,
        timingAge: (value, context) => {
            initializeSerializers('Quantity');
            return FhirResourceSerializer.serialize(value, QuantitySerializer, context);
        },
        timingPeriod: (value, context) => {
            initializeSerializers('Period');
            return FhirResourceSerializer.serialize(value, PeriodSerializer, context);
        },
        timingDuration: (value, context) => {
            initializeSerializers('Quantity');
            return FhirResourceSerializer.serialize(value, QuantitySerializer, context);
        },
        timingRange: (value, context) => {
            initializeSerializers('Range');
            return FhirResourceSerializer.serialize(value, RangeSerializer, context);
        },
        timingTiming: (value, context) => {
            initializeSerializers('Timing');
            return FhirResourceSerializer.serialize(value, TimingSerializer, context);
        },
        participant: (value, context) => {
            initializeSerializers('Reference');
            return FhirResourceSerializer.serializeArray(value, ReferenceSerializer, context);
        },
        type: (value, context) => {
            initializeSerializers('CodeableConcept');
            return FhirResourceSerializer.serialize(value, CodeableConceptSerializer, context);
        },
        groupingBehavior: null,
        selectionBehavior: null,
        requiredBehavior: null,
        precheckBehavior: null,
        cardinalityBehavior: null,
        resource: (value, context) => {
            initializeSerializers('Reference');
            return FhirResourceSerializer.serialize(value, ReferenceSerializer, context);
        },
        action: (value, context) => {
            initializeSerializers('RequestGroupAction');
            return FhirResourceSerializer.serializeArray(value, RequestGroupActionSerializer, context);
        }
    };

    /**
     * This methods cleans the raw json by removing additional fields which are not defined
     * according to FHIR Specs
     * @param {any} rawJson
     * @param {Object} context
     * @returns {any} Cleaned object
     */
    static serialize(rawJson, context = {}) {
        if (!rawJson) return rawJson;

        // Handle array case
        if (Array.isArray(rawJson)) {
            return rawJson.map(item => RequestGroupActionSerializer.serialize(item, context));
        }

        // Handle non-object case
        if (typeof rawJson !== 'object') return rawJson;

        Object.keys(rawJson).forEach(propertyName => {
            const value = rawJson[propertyName];

            if (value === null || value === undefined) {
                delete rawJson[propertyName];
                return;
            }

            if (propertyName in RequestGroupActionSerializer.propertyToSerializerMap) {
                if (RequestGroupActionSerializer.propertyToSerializerMap[propertyName]) {
                    const serializedValue = RequestGroupActionSerializer.propertyToSerializerMap[propertyName](value, context);
                    if (serializedValue === null || serializedValue === undefined) {
                        delete rawJson[propertyName];
                    } else {
                        rawJson[propertyName] = serializedValue;
                    }
                }
            } else {
                delete rawJson[propertyName];
            }
        });

        return rawJson;
    }
}

module.exports = RequestGroupActionSerializer;
