// This file is auto-generated by generate_classes so do not edit manually

const MetaSerializer = require('../complex_types/meta.js');
const NarrativeSerializer = require('../complex_types/narrative.js');
const ResourceContainerSerializer = require('../simple_types/resourceContainer.js');
const ExtensionSerializer = require('../complex_types/extension.js');
const IdentifierSerializer = require('../complex_types/identifier.js');
const CodeableConceptSerializer = require('../complex_types/codeableConcept.js');
const ReferenceSerializer = require('../complex_types/reference.js');
const PeriodSerializer = require('../complex_types/period.js');
const ClinicalImpressionInvestigationSerializer = require('../backbone_elements/clinicalImpressionInvestigation.js');
const ClinicalImpressionFindingSerializer = require('../backbone_elements/clinicalImpressionFinding.js');
const AnnotationSerializer = require('../complex_types/annotation.js');

class ClinicalImpressionSerializer {
    static propertyToSerializerMap = {
        id: null,
        meta: (value) => MetaSerializer.serialize(value),
        implicitRules: null,
        language: null,
        text: (value) => NarrativeSerializer.serialize(value),
        contained: (value) => ResourceContainerSerializer.serialize(value),
        extension: (value) => ExtensionSerializer.serialize(value),
        modifierExtension: (value) => ExtensionSerializer.serialize(value),
        identifier: (value) => IdentifierSerializer.serialize(value),
        status: null,
        statusReason: (value) => CodeableConceptSerializer.serialize(value),
        code: (value) => CodeableConceptSerializer.serialize(value),
        description: null,
        subject: (value) => ReferenceSerializer.serialize(value),
        encounter: (value) => ReferenceSerializer.serialize(value),
        effectiveDateTime: null,
        effectivePeriod: (value) => PeriodSerializer.serialize(value),
        date: null,
        assessor: (value) => ReferenceSerializer.serialize(value),
        previous: (value) => ReferenceSerializer.serialize(value),
        problem: (value) => ReferenceSerializer.serialize(value),
        investigation: (value) => ClinicalImpressionInvestigationSerializer.serialize(value),
        protocol: null,
        summary: null,
        finding: (value) => ClinicalImpressionFindingSerializer.serialize(value),
        prognosisCodeableConcept: (value) => CodeableConceptSerializer.serialize(value),
        prognosisReference: (value) => ReferenceSerializer.serialize(value),
        supportingInfo: (value) => ReferenceSerializer.serialize(value),
        note: (value) => AnnotationSerializer.serialize(value),
        resourceType: null
    };

    /**
     * This methods cleans the raw json by removing additional fields which are not defined
     * according to FHIR Specs
     * @param {any} rawJson
     * @returns {any} Cleaned object
     */
    static serialize(rawJson) {
        if (!rawJson) return rawJson;

        // Handle array case
        if (Array.isArray(rawJson)) {
            return rawJson.map(item => ClinicalImpressionSerializer.serialize(item));
        }

        // Handle non-object case
        if (typeof rawJson !== 'object') return rawJson;

        Object.keys(rawJson).forEach(propertyName => {
            const value = rawJson[propertyName];

            if (value === null || value === undefined) {
                delete rawJson[propertyName];
                return;
            }

            if (propertyName in ClinicalImpressionSerializer.propertyToSerializerMap) {
                if (ClinicalImpressionSerializer.propertyToSerializerMap[propertyName]) {
                    const serializedValue = ClinicalImpressionSerializer.propertyToSerializerMap[propertyName](value);
                    if (serializedValue === null || serializedValue === undefined) {
                        delete rawJson[propertyName];
                    } else {
                        rawJson[propertyName] = serializedValue;
                    }
                }
            } else {
                delete rawJson[propertyName];
            }
        });

        return rawJson;
    }
}

module.exports = ClinicalImpressionSerializer;