// This file is auto-generated by generate_classes so do not edit manually

/** @type {import('../complex_types/meta.js')} */
let Meta;
/** @type {import('../complex_types/narrative.js')} */
let Narrative;
/** @type {import('../simple_types/resourceContainer.js')} */
let ResourceContainer;
/** @type {import('../complex_types/extension.js')} */
let Extension;
/** @type {import('../complex_types/identifier.js')} */
let Identifier;
/** @type {import('../complex_types/reference.js')} */
let Reference;
/** @type {import('../backbone_elements/deviceUdiCarrier.js')} */
let DeviceUdiCarrier;
/** @type {import('../complex_types/codeableConcept.js')} */
let CodeableConcept;
/** @type {import('../backbone_elements/deviceDeviceName.js')} */
let DeviceDeviceName;
/** @type {import('../backbone_elements/deviceSpecialization.js')} */
let DeviceSpecialization;
/** @type {import('../backbone_elements/deviceVersion.js')} */
let DeviceVersion;
/** @type {import('../backbone_elements/deviceProperty.js')} */
let DeviceProperty;
/** @type {import('../complex_types/contactPoint.js')} */
let ContactPoint;
/** @type {import('../complex_types/annotation.js')} */
let Annotation;

/**
 * Lazy loads the required serializers
 * It esnures that require is called only once for each serializer to minimize the call stack for require()
 * @returns {any}
 */
function initializeSerializers(serializerName) {
    initializeResourceSerializer()
    if (serializerName === 'Meta' && !Meta) {
        Meta = require('../complex_types/meta.js');
        return Meta;
    }
    if (serializerName === 'Narrative' && !Narrative) {
        Narrative = require('../complex_types/narrative.js');
        return Narrative;
    }
    if (serializerName === 'ResourceContainer' && !ResourceContainer) {
        ResourceContainer = require('../simple_types/resourceContainer.js');
        return ResourceContainer;
    }
    if (serializerName === 'Extension' && !Extension) {
        Extension = require('../complex_types/extension.js');
        return Extension;
    }
    if (serializerName === 'Identifier' && !Identifier) {
        Identifier = require('../complex_types/identifier.js');
        return Identifier;
    }
    if (serializerName === 'Reference' && !Reference) {
        Reference = require('../complex_types/reference.js');
        return Reference;
    }
    if (serializerName === 'DeviceUdiCarrier' && !DeviceUdiCarrier) {
        DeviceUdiCarrier = require('../backbone_elements/deviceUdiCarrier.js');
        return DeviceUdiCarrier;
    }
    if (serializerName === 'CodeableConcept' && !CodeableConcept) {
        CodeableConcept = require('../complex_types/codeableConcept.js');
        return CodeableConcept;
    }
    if (serializerName === 'DeviceDeviceName' && !DeviceDeviceName) {
        DeviceDeviceName = require('../backbone_elements/deviceDeviceName.js');
        return DeviceDeviceName;
    }
    if (serializerName === 'DeviceSpecialization' && !DeviceSpecialization) {
        DeviceSpecialization = require('../backbone_elements/deviceSpecialization.js');
        return DeviceSpecialization;
    }
    if (serializerName === 'DeviceVersion' && !DeviceVersion) {
        DeviceVersion = require('../backbone_elements/deviceVersion.js');
        return DeviceVersion;
    }
    if (serializerName === 'DeviceProperty' && !DeviceProperty) {
        DeviceProperty = require('../backbone_elements/deviceProperty.js');
        return DeviceProperty;
    }
    if (serializerName === 'ContactPoint' && !ContactPoint) {
        ContactPoint = require('../complex_types/contactPoint.js');
        return ContactPoint;
    }
    if (serializerName === 'Annotation' && !Annotation) {
        Annotation = require('../complex_types/annotation.js');
        return Annotation;
    }
}

/** @type {import('../../../fhirResourceSerializer.js').FhirResourceSerializer} */
let FhirResourceSerializer;

function initializeResourceSerializer() {
    if (!FhirResourceSerializer) {
        FhirResourceSerializer = require('../../../fhirResourceSerializer.js').FhirResourceSerializer;
    }

    return FhirResourceSerializer;
}

class DeviceSerializer {
    static propertyToSerializerMap = {
        id: null,
        meta: (value) => {
            initializeSerializers('Meta');
            return FhirResourceSerializer.serialize(value, Meta);
        },
        implicitRules: null,
        language: null,
        text: (value) => {
            initializeSerializers('Narrative');
            return FhirResourceSerializer.serialize(value, Narrative);
        },
        contained: (value) => {
            initializeSerializers('ResourceContainer');
            return FhirResourceSerializer.serializeArray(value);
        },
        extension: (value) => {
            initializeSerializers('Extension');
            return FhirResourceSerializer.serializeArray(value, Extension);
        },
        modifierExtension: (value) => {
            initializeSerializers('Extension');
            return FhirResourceSerializer.serializeArray(value, Extension);
        },
        identifier: (value) => {
            initializeSerializers('Identifier');
            return FhirResourceSerializer.serializeArray(value, Identifier);
        },
        definition: (value) => {
            initializeSerializers('Reference');
            return FhirResourceSerializer.serialize(value, Reference);
        },
        udiCarrier: (value) => {
            initializeSerializers('DeviceUdiCarrier');
            return FhirResourceSerializer.serializeArray(value, DeviceUdiCarrier);
        },
        status: null,
        statusReason: (value) => {
            initializeSerializers('CodeableConcept');
            return FhirResourceSerializer.serializeArray(value, CodeableConcept);
        },
        distinctIdentifier: null,
        manufacturer: null,
        manufactureDate: null,
        expirationDate: null,
        lotNumber: null,
        serialNumber: null,
        deviceName: (value) => {
            initializeSerializers('DeviceDeviceName');
            return FhirResourceSerializer.serializeArray(value, DeviceDeviceName);
        },
        modelNumber: null,
        partNumber: null,
        type: (value) => {
            initializeSerializers('CodeableConcept');
            return FhirResourceSerializer.serialize(value, CodeableConcept);
        },
        specialization: (value) => {
            initializeSerializers('DeviceSpecialization');
            return FhirResourceSerializer.serializeArray(value, DeviceSpecialization);
        },
        version: (value) => {
            initializeSerializers('DeviceVersion');
            return FhirResourceSerializer.serializeArray(value, DeviceVersion);
        },
        property: (value) => {
            initializeSerializers('DeviceProperty');
            return FhirResourceSerializer.serializeArray(value, DeviceProperty);
        },
        patient: (value) => {
            initializeSerializers('Reference');
            return FhirResourceSerializer.serialize(value, Reference);
        },
        owner: (value) => {
            initializeSerializers('Reference');
            return FhirResourceSerializer.serialize(value, Reference);
        },
        contact: (value) => {
            initializeSerializers('ContactPoint');
            return FhirResourceSerializer.serializeArray(value, ContactPoint);
        },
        location: (value) => {
            initializeSerializers('Reference');
            return FhirResourceSerializer.serialize(value, Reference);
        },
        url: null,
        note: (value) => {
            initializeSerializers('Annotation');
            return FhirResourceSerializer.serializeArray(value, Annotation);
        },
        safety: (value) => {
            initializeSerializers('CodeableConcept');
            return FhirResourceSerializer.serializeArray(value, CodeableConcept);
        },
        parent: (value) => {
            initializeSerializers('Reference');
            return FhirResourceSerializer.serialize(value, Reference);
        },
        resourceType: null
    };

    /**
     * This methods cleans the raw json by removing additional fields which are not defined
     * according to FHIR Specs
     * @param {any} rawJson
     * @returns {any} Cleaned object
     */
    static serialize(rawJson) {
        if (!rawJson) return rawJson;

        // Handle array case
        if (Array.isArray(rawJson)) {
            return rawJson.map(item => DeviceSerializer.serialize(item));
        }

        // Handle non-object case
        if (typeof rawJson !== 'object') return rawJson;

        Object.keys(rawJson).forEach(propertyName => {
            const value = rawJson[propertyName];

            if (value === null || value === undefined) {
                delete rawJson[propertyName];
                return;
            }

            if (propertyName in DeviceSerializer.propertyToSerializerMap) {
                if (DeviceSerializer.propertyToSerializerMap[propertyName]) {
                    const serializedValue = DeviceSerializer.propertyToSerializerMap[propertyName](value);
                    if (serializedValue === null || serializedValue === undefined) {
                        delete rawJson[propertyName];
                    } else {
                        rawJson[propertyName] = serializedValue;
                    }
                }
            } else {
                delete rawJson[propertyName];
            }
        });

        return rawJson;
    }
}

module.exports = DeviceSerializer;
