// This file is auto-generated by generate_classes so do not edit manually

const MetaSerializer = require('../complex_types/meta.js');
const NarrativeSerializer = require('../complex_types/narrative.js');
const ResourceContainerSerializer = require('../simple_types/resourceContainer.js');
const ExtensionSerializer = require('../complex_types/extension.js');
const IdentifierSerializer = require('../complex_types/identifier.js');
const CodeableConceptSerializer = require('../complex_types/codeableConcept.js');
const ReferenceSerializer = require('../complex_types/reference.js');
const PeriodSerializer = require('../complex_types/period.js');
const ExplanationOfBenefitRelatedSerializer = require('../backbone_elements/explanationOfBenefitRelated.js');
const ExplanationOfBenefitPayeeSerializer = require('../backbone_elements/explanationOfBenefitPayee.js');
const ExplanationOfBenefitCareTeamSerializer = require('../backbone_elements/explanationOfBenefitCareTeam.js');
const ExplanationOfBenefitSupportingInfoSerializer = require('../backbone_elements/explanationOfBenefitSupportingInfo.js');
const ExplanationOfBenefitDiagnosisSerializer = require('../backbone_elements/explanationOfBenefitDiagnosis.js');
const ExplanationOfBenefitProcedureSerializer = require('../backbone_elements/explanationOfBenefitProcedure.js');
const ExplanationOfBenefitInsuranceSerializer = require('../backbone_elements/explanationOfBenefitInsurance.js');
const ExplanationOfBenefitAccidentSerializer = require('../backbone_elements/explanationOfBenefitAccident.js');
const ExplanationOfBenefitItemSerializer = require('../backbone_elements/explanationOfBenefitItem.js');
const ExplanationOfBenefitAddItemSerializer = require('../backbone_elements/explanationOfBenefitAddItem.js');
const ExplanationOfBenefitAdjudicationSerializer = require('../backbone_elements/explanationOfBenefitAdjudication.js');
const ExplanationOfBenefitTotalSerializer = require('../backbone_elements/explanationOfBenefitTotal.js');
const ExplanationOfBenefitPaymentSerializer = require('../backbone_elements/explanationOfBenefitPayment.js');
const AttachmentSerializer = require('../complex_types/attachment.js');
const ExplanationOfBenefitProcessNoteSerializer = require('../backbone_elements/explanationOfBenefitProcessNote.js');
const ExplanationOfBenefitBenefitBalanceSerializer = require('../backbone_elements/explanationOfBenefitBenefitBalance.js');

class ExplanationOfBenefitSerializer {
    static propertyToSerializerMap = {
        id: null,
        meta: (value) => MetaSerializer.serialize(value),
        implicitRules: null,
        language: null,
        text: (value) => NarrativeSerializer.serialize(value),
        contained: (value) => ResourceContainerSerializer.serialize(value),
        extension: (value) => ExtensionSerializer.serialize(value),
        modifierExtension: (value) => ExtensionSerializer.serialize(value),
        identifier: (value) => IdentifierSerializer.serialize(value),
        status: null,
        type: (value) => CodeableConceptSerializer.serialize(value),
        subType: (value) => CodeableConceptSerializer.serialize(value),
        use: null,
        patient: (value) => ReferenceSerializer.serialize(value),
        billablePeriod: (value) => PeriodSerializer.serialize(value),
        created: null,
        enterer: (value) => ReferenceSerializer.serialize(value),
        insurer: (value) => ReferenceSerializer.serialize(value),
        provider: (value) => ReferenceSerializer.serialize(value),
        priority: (value) => CodeableConceptSerializer.serialize(value),
        fundsReserveRequested: (value) => CodeableConceptSerializer.serialize(value),
        fundsReserve: (value) => CodeableConceptSerializer.serialize(value),
        related: (value) => ExplanationOfBenefitRelatedSerializer.serialize(value),
        prescription: (value) => ReferenceSerializer.serialize(value),
        originalPrescription: (value) => ReferenceSerializer.serialize(value),
        payee: (value) => ExplanationOfBenefitPayeeSerializer.serialize(value),
        referral: (value) => ReferenceSerializer.serialize(value),
        facility: (value) => ReferenceSerializer.serialize(value),
        claim: (value) => ReferenceSerializer.serialize(value),
        claimResponse: (value) => ReferenceSerializer.serialize(value),
        outcome: null,
        disposition: null,
        preAuthRef: null,
        preAuthRefPeriod: (value) => PeriodSerializer.serialize(value),
        careTeam: (value) => ExplanationOfBenefitCareTeamSerializer.serialize(value),
        supportingInfo: (value) => ExplanationOfBenefitSupportingInfoSerializer.serialize(value),
        diagnosis: (value) => ExplanationOfBenefitDiagnosisSerializer.serialize(value),
        procedure: (value) => ExplanationOfBenefitProcedureSerializer.serialize(value),
        precedence: null,
        insurance: (value) => ExplanationOfBenefitInsuranceSerializer.serialize(value),
        accident: (value) => ExplanationOfBenefitAccidentSerializer.serialize(value),
        item: (value) => ExplanationOfBenefitItemSerializer.serialize(value),
        addItem: (value) => ExplanationOfBenefitAddItemSerializer.serialize(value),
        adjudication: (value) => ExplanationOfBenefitAdjudicationSerializer.serialize(value),
        total: (value) => ExplanationOfBenefitTotalSerializer.serialize(value),
        payment: (value) => ExplanationOfBenefitPaymentSerializer.serialize(value),
        formCode: (value) => CodeableConceptSerializer.serialize(value),
        form: (value) => AttachmentSerializer.serialize(value),
        processNote: (value) => ExplanationOfBenefitProcessNoteSerializer.serialize(value),
        benefitPeriod: (value) => PeriodSerializer.serialize(value),
        benefitBalance: (value) => ExplanationOfBenefitBenefitBalanceSerializer.serialize(value),
        resourceType: null
    };

    /**
     * This methods cleans the raw json by removing additional fields which are not defined
     * according to FHIR Specs
     * @param {any} rawJson
     * @returns {any} Cleaned object
     */
    static serialize(rawJson) {
        if (!rawJson) return rawJson;

        // Handle array case
        if (Array.isArray(rawJson)) {
            return rawJson.map(item => ExplanationOfBenefitSerializer.serialize(item));
        }

        // Handle non-object case
        if (typeof rawJson !== 'object') return rawJson;

        Object.keys(rawJson).forEach(propertyName => {
            const value = rawJson[propertyName];

            if (value === null || value === undefined) {
                delete rawJson[propertyName];
                return;
            }

            if (propertyName in ExplanationOfBenefitSerializer.propertyToSerializerMap) {
                if (ExplanationOfBenefitSerializer.propertyToSerializerMap[propertyName]) {
                    const serializedValue = ExplanationOfBenefitSerializer.propertyToSerializerMap[propertyName](value);
                    if (serializedValue === null || serializedValue === undefined) {
                        delete rawJson[propertyName];
                    } else {
                        rawJson[propertyName] = serializedValue;
                    }
                }
            } else {
                delete rawJson[propertyName];
            }
        });

        return rawJson;
    }
}

module.exports = ExplanationOfBenefitSerializer;