// This file is auto-generated by generate_classes so do not edit manually

const MetaSerializer = require('../complex_types/meta.js');
const NarrativeSerializer = require('../complex_types/narrative.js');
const ResourceContainerSerializer = require('../simple_types/resourceContainer.js');
const ExtensionSerializer = require('../complex_types/extension.js');
const IdentifierSerializer = require('../complex_types/identifier.js');
const CodeableConceptSerializer = require('../complex_types/codeableConcept.js');
const ReferenceSerializer = require('../complex_types/reference.js');
const AnnotationSerializer = require('../complex_types/annotation.js');
const DataRequirementSerializer = require('../complex_types/dataRequirement.js');

class GuidanceResponseSerializer {
    static propertyToSerializerMap = {
        id: null,
        meta: (value) => MetaSerializer.serialize(value),
        implicitRules: null,
        language: null,
        text: (value) => NarrativeSerializer.serialize(value),
        contained: (value) => ResourceContainerSerializer.serialize(value),
        extension: (value) => ExtensionSerializer.serialize(value),
        modifierExtension: (value) => ExtensionSerializer.serialize(value),
        requestIdentifier: (value) => IdentifierSerializer.serialize(value),
        identifier: (value) => IdentifierSerializer.serialize(value),
        moduleUri: null,
        moduleCanonical: null,
        moduleCodeableConcept: (value) => CodeableConceptSerializer.serialize(value),
        status: null,
        subject: (value) => ReferenceSerializer.serialize(value),
        encounter: (value) => ReferenceSerializer.serialize(value),
        occurrenceDateTime: null,
        performer: (value) => ReferenceSerializer.serialize(value),
        reasonCode: (value) => CodeableConceptSerializer.serialize(value),
        reasonReference: (value) => ReferenceSerializer.serialize(value),
        note: (value) => AnnotationSerializer.serialize(value),
        evaluationMessage: (value) => ReferenceSerializer.serialize(value),
        outputParameters: (value) => ReferenceSerializer.serialize(value),
        result: (value) => ReferenceSerializer.serialize(value),
        dataRequirement: (value) => DataRequirementSerializer.serialize(value),
        resourceType: null
    };

    /**
     * This methods cleans the raw json by removing additional fields which are not defined
     * according to FHIR Specs
     * @param {any} rawJson
     * @returns {any} Cleaned object
     */
    static serialize(rawJson) {
        if (!rawJson) return rawJson;

        // Handle array case
        if (Array.isArray(rawJson)) {
            return rawJson.map(item => GuidanceResponseSerializer.serialize(item));
        }

        // Handle non-object case
        if (typeof rawJson !== 'object') return rawJson;

        Object.keys(rawJson).forEach(propertyName => {
            const value = rawJson[propertyName];

            if (value === null || value === undefined) {
                delete rawJson[propertyName];
                return;
            }

            if (propertyName in GuidanceResponseSerializer.propertyToSerializerMap) {
                if (GuidanceResponseSerializer.propertyToSerializerMap[propertyName]) {
                    const serializedValue = GuidanceResponseSerializer.propertyToSerializerMap[propertyName](value);
                    if (serializedValue === null || serializedValue === undefined) {
                        delete rawJson[propertyName];
                    } else {
                        rawJson[propertyName] = serializedValue;
                    }
                }
            } else {
                delete rawJson[propertyName];
            }
        });

        return rawJson;
    }
}

module.exports = GuidanceResponseSerializer;