// This file is auto-generated by generate_classes so do not edit manually

const MetaSerializer = require('../complex_types/meta.js');
const NarrativeSerializer = require('../complex_types/narrative.js');
const ResourceContainerSerializer = require('../simple_types/resourceContainer.js');
const ExtensionSerializer = require('../complex_types/extension.js');
const ContactDetailSerializer = require('../complex_types/contactDetail.js');
const UsageContextSerializer = require('../complex_types/usageContext.js');
const CodeableConceptSerializer = require('../complex_types/codeableConcept.js');
const TerminologyCapabilitiesSoftwareSerializer = require('../backbone_elements/terminologyCapabilitiesSoftware.js');
const TerminologyCapabilitiesImplementationSerializer = require('../backbone_elements/terminologyCapabilitiesImplementation.js');
const TerminologyCapabilitiesCodeSystemSerializer = require('../backbone_elements/terminologyCapabilitiesCodeSystem.js');
const TerminologyCapabilitiesExpansionSerializer = require('../backbone_elements/terminologyCapabilitiesExpansion.js');
const TerminologyCapabilitiesValidateCodeSerializer = require('../backbone_elements/terminologyCapabilitiesValidateCode.js');
const TerminologyCapabilitiesTranslationSerializer = require('../backbone_elements/terminologyCapabilitiesTranslation.js');
const TerminologyCapabilitiesClosureSerializer = require('../backbone_elements/terminologyCapabilitiesClosure.js');

class TerminologyCapabilitiesSerializer {
    static propertyToSerializerMap = {
        id: null,
        meta: (value) => MetaSerializer.serialize(value),
        implicitRules: null,
        language: null,
        text: (value) => NarrativeSerializer.serialize(value),
        contained: (value) => ResourceContainerSerializer.serialize(value),
        extension: (value) => ExtensionSerializer.serialize(value),
        modifierExtension: (value) => ExtensionSerializer.serialize(value),
        url: null,
        version: null,
        name: null,
        title: null,
        status: null,
        experimental: null,
        date: null,
        publisher: null,
        contact: (value) => ContactDetailSerializer.serialize(value),
        description: null,
        useContext: (value) => UsageContextSerializer.serialize(value),
        jurisdiction: (value) => CodeableConceptSerializer.serialize(value),
        purpose: null,
        copyright: null,
        kind: null,
        software: (value) => TerminologyCapabilitiesSoftwareSerializer.serialize(value),
        implementation: (value) => TerminologyCapabilitiesImplementationSerializer.serialize(value),
        lockedDate: null,
        codeSystem: (value) => TerminologyCapabilitiesCodeSystemSerializer.serialize(value),
        expansion: (value) => TerminologyCapabilitiesExpansionSerializer.serialize(value),
        codeSearch: null,
        validateCode: (value) => TerminologyCapabilitiesValidateCodeSerializer.serialize(value),
        translation: (value) => TerminologyCapabilitiesTranslationSerializer.serialize(value),
        closure: (value) => TerminologyCapabilitiesClosureSerializer.serialize(value),
        resourceType: null
    };

    /**
     * This methods cleans the raw json by removing additional fields which are not defined
     * according to FHIR Specs
     * @param {any} rawJson
     * @returns {any} Cleaned object
     */
    static serialize(rawJson) {
        if (!rawJson) return rawJson;

        // Handle array case
        if (Array.isArray(rawJson)) {
            return rawJson.map(item => TerminologyCapabilitiesSerializer.serialize(item));
        }

        // Handle non-object case
        if (typeof rawJson !== 'object') return rawJson;

        Object.keys(rawJson).forEach(propertyName => {
            const value = rawJson[propertyName];

            if (value === null || value === undefined) {
                delete rawJson[propertyName];
                return;
            }

            if (propertyName in TerminologyCapabilitiesSerializer.propertyToSerializerMap) {
                if (TerminologyCapabilitiesSerializer.propertyToSerializerMap[propertyName]) {
                    const serializedValue = TerminologyCapabilitiesSerializer.propertyToSerializerMap[propertyName](value);
                    if (serializedValue === null || serializedValue === undefined) {
                        delete rawJson[propertyName];
                    } else {
                        rawJson[propertyName] = serializedValue;
                    }
                }
            } else {
                delete rawJson[propertyName];
            }
        });

        return rawJson;
    }
}

module.exports = TerminologyCapabilitiesSerializer;