// This file is auto-generated by generate_classes so do not edit manually

/** @type {import('../complex_types/meta.js')} */
let Meta;
/** @type {import('../complex_types/narrative.js')} */
let Narrative;
/** @type {import('../simple_types/resourceContainer.js')} */
let ResourceContainer;
/** @type {import('../complex_types/extension.js')} */
let Extension;
/** @type {import('../complex_types/identifier.js')} */
let Identifier;
/** @type {import('../complex_types/contactDetail.js')} */
let ContactDetail;
/** @type {import('../complex_types/usageContext.js')} */
let UsageContext;
/** @type {import('../complex_types/codeableConcept.js')} */
let CodeableConcept;
/** @type {import('../backbone_elements/testScriptOrigin.js')} */
let TestScriptOrigin;
/** @type {import('../backbone_elements/testScriptDestination.js')} */
let TestScriptDestination;
/** @type {import('../backbone_elements/testScriptMetadata.js')} */
let TestScriptMetadata;
/** @type {import('../backbone_elements/testScriptFixture.js')} */
let TestScriptFixture;
/** @type {import('../complex_types/reference.js')} */
let Reference;
/** @type {import('../backbone_elements/testScriptVariable.js')} */
let TestScriptVariable;
/** @type {import('../backbone_elements/testScriptSetup.js')} */
let TestScriptSetup;
/** @type {import('../backbone_elements/testScriptTest.js')} */
let TestScriptTest;
/** @type {import('../backbone_elements/testScriptTeardown.js')} */
let TestScriptTeardown;

/**
 * Lazy loads the required serializers
 * It esnures that require is called only once for each serializer to minimize the call stack for require()
 * @returns {any}
 */
function initializeSerializers(serializerName) {
    initializeResourceSerializer()
    if (serializerName === 'Meta' && !Meta) {
        Meta = require('../complex_types/meta.js');
        return Meta;
    }
    if (serializerName === 'Narrative' && !Narrative) {
        Narrative = require('../complex_types/narrative.js');
        return Narrative;
    }
    if (serializerName === 'ResourceContainer' && !ResourceContainer) {
        ResourceContainer = require('../simple_types/resourceContainer.js');
        return ResourceContainer;
    }
    if (serializerName === 'Extension' && !Extension) {
        Extension = require('../complex_types/extension.js');
        return Extension;
    }
    if (serializerName === 'Identifier' && !Identifier) {
        Identifier = require('../complex_types/identifier.js');
        return Identifier;
    }
    if (serializerName === 'ContactDetail' && !ContactDetail) {
        ContactDetail = require('../complex_types/contactDetail.js');
        return ContactDetail;
    }
    if (serializerName === 'UsageContext' && !UsageContext) {
        UsageContext = require('../complex_types/usageContext.js');
        return UsageContext;
    }
    if (serializerName === 'CodeableConcept' && !CodeableConcept) {
        CodeableConcept = require('../complex_types/codeableConcept.js');
        return CodeableConcept;
    }
    if (serializerName === 'TestScriptOrigin' && !TestScriptOrigin) {
        TestScriptOrigin = require('../backbone_elements/testScriptOrigin.js');
        return TestScriptOrigin;
    }
    if (serializerName === 'TestScriptDestination' && !TestScriptDestination) {
        TestScriptDestination = require('../backbone_elements/testScriptDestination.js');
        return TestScriptDestination;
    }
    if (serializerName === 'TestScriptMetadata' && !TestScriptMetadata) {
        TestScriptMetadata = require('../backbone_elements/testScriptMetadata.js');
        return TestScriptMetadata;
    }
    if (serializerName === 'TestScriptFixture' && !TestScriptFixture) {
        TestScriptFixture = require('../backbone_elements/testScriptFixture.js');
        return TestScriptFixture;
    }
    if (serializerName === 'Reference' && !Reference) {
        Reference = require('../complex_types/reference.js');
        return Reference;
    }
    if (serializerName === 'TestScriptVariable' && !TestScriptVariable) {
        TestScriptVariable = require('../backbone_elements/testScriptVariable.js');
        return TestScriptVariable;
    }
    if (serializerName === 'TestScriptSetup' && !TestScriptSetup) {
        TestScriptSetup = require('../backbone_elements/testScriptSetup.js');
        return TestScriptSetup;
    }
    if (serializerName === 'TestScriptTest' && !TestScriptTest) {
        TestScriptTest = require('../backbone_elements/testScriptTest.js');
        return TestScriptTest;
    }
    if (serializerName === 'TestScriptTeardown' && !TestScriptTeardown) {
        TestScriptTeardown = require('../backbone_elements/testScriptTeardown.js');
        return TestScriptTeardown;
    }
}

/** @type {import('../../../fhirResourceSerializer.js').FhirResourceSerializer} */
let FhirResourceSerializer;

function initializeResourceSerializer() {
    if (!FhirResourceSerializer) {
        FhirResourceSerializer = require('../../../fhirResourceSerializer.js').FhirResourceSerializer;
    }

    return FhirResourceSerializer;
}

class TestScriptSerializer {
    static propertyToSerializerMap = {
        id: null,
        meta: (value) => {
            initializeSerializers('Meta');
            return FhirResourceSerializer.serialize(value, Meta);
        },
        implicitRules: null,
        language: null,
        text: (value) => {
            initializeSerializers('Narrative');
            return FhirResourceSerializer.serialize(value, Narrative);
        },
        contained: (value) => {
            initializeSerializers('ResourceContainer');
            return FhirResourceSerializer.serializeArray(value);
        },
        extension: (value) => {
            initializeSerializers('Extension');
            return FhirResourceSerializer.serializeArray(value, Extension);
        },
        modifierExtension: (value) => {
            initializeSerializers('Extension');
            return FhirResourceSerializer.serializeArray(value, Extension);
        },
        url: null,
        identifier: (value) => {
            initializeSerializers('Identifier');
            return FhirResourceSerializer.serialize(value, Identifier);
        },
        version: null,
        name: null,
        title: null,
        status: null,
        experimental: null,
        date: null,
        publisher: null,
        contact: (value) => {
            initializeSerializers('ContactDetail');
            return FhirResourceSerializer.serializeArray(value, ContactDetail);
        },
        description: null,
        useContext: (value) => {
            initializeSerializers('UsageContext');
            return FhirResourceSerializer.serializeArray(value, UsageContext);
        },
        jurisdiction: (value) => {
            initializeSerializers('CodeableConcept');
            return FhirResourceSerializer.serializeArray(value, CodeableConcept);
        },
        purpose: null,
        copyright: null,
        origin: (value) => {
            initializeSerializers('TestScriptOrigin');
            return FhirResourceSerializer.serializeArray(value, TestScriptOrigin);
        },
        destination: (value) => {
            initializeSerializers('TestScriptDestination');
            return FhirResourceSerializer.serializeArray(value, TestScriptDestination);
        },
        metadata: (value) => {
            initializeSerializers('TestScriptMetadata');
            return FhirResourceSerializer.serialize(value, TestScriptMetadata);
        },
        fixture: (value) => {
            initializeSerializers('TestScriptFixture');
            return FhirResourceSerializer.serializeArray(value, TestScriptFixture);
        },
        profile: (value) => {
            initializeSerializers('Reference');
            return FhirResourceSerializer.serializeArray(value, Reference);
        },
        variable: (value) => {
            initializeSerializers('TestScriptVariable');
            return FhirResourceSerializer.serializeArray(value, TestScriptVariable);
        },
        setup: (value) => {
            initializeSerializers('TestScriptSetup');
            return FhirResourceSerializer.serialize(value, TestScriptSetup);
        },
        test: (value) => {
            initializeSerializers('TestScriptTest');
            return FhirResourceSerializer.serializeArray(value, TestScriptTest);
        },
        teardown: (value) => {
            initializeSerializers('TestScriptTeardown');
            return FhirResourceSerializer.serialize(value, TestScriptTeardown);
        },
        resourceType: null
    };

    /**
     * This methods cleans the raw json by removing additional fields which are not defined
     * according to FHIR Specs
     * @param {any} rawJson
     * @returns {any} Cleaned object
     */
    static serialize(rawJson) {
        if (!rawJson) return rawJson;

        // Handle array case
        if (Array.isArray(rawJson)) {
            return rawJson.map(item => TestScriptSerializer.serialize(item));
        }

        // Handle non-object case
        if (typeof rawJson !== 'object') return rawJson;

        Object.keys(rawJson).forEach(propertyName => {
            const value = rawJson[propertyName];

            if (value === null || value === undefined) {
                delete rawJson[propertyName];
                return;
            }

            if (propertyName in TestScriptSerializer.propertyToSerializerMap) {
                if (TestScriptSerializer.propertyToSerializerMap[propertyName]) {
                    const serializedValue = TestScriptSerializer.propertyToSerializerMap[propertyName](value);
                    if (serializedValue === null || serializedValue === undefined) {
                        delete rawJson[propertyName];
                    } else {
                        rawJson[propertyName] = serializedValue;
                    }
                }
            } else {
                delete rawJson[propertyName];
            }
        });

        return rawJson;
    }
}

module.exports = TestScriptSerializer;
