name: 'Commit Message Check'
on:
  pull_request:
    types: [opened, edited, reopened, synchronize]
  push:
    branches: [main, 'releases/*']

jobs:
  check-commit-message:
    name: Check Commit Message
    runs-on: ubuntu-latest
    steps:
      - name: Check For Issue Key
        uses: gsactions/commit-message-checker@v2
        with:
          pattern: '^(Bump|Merge|Revert|Reapply|fix\(security\):|\[Aikido\]|build\(deps(-dev)?\): bump|([A-Z]+-[0-9]+))\s+.+'
          flags: 'gm'
          error: 'Commit message must begin with a JIRA Issue Key: e.g. HP-123 <message>'
