name: Deploy Ephemeral Environment

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize
      - labeled

jobs:
  build-ephemeral-image:
    if:
      ${{ contains(github.event.pull_request.labels.*.name,
      'ephemeral-environment') }}
    uses: ./.github/workflows/build-ephemeral-image.yml
    secrets: inherit

  deploy-ephemeral-environment:
    needs: build-ephemeral-image
    uses: icanbwell/actions/.github/workflows/deploy-ephemeral-environment.yml@main
    secrets: inherit
    with:
      organization: ${{ github.event.organization.login }}
      repository: ${{ github.event.repository.name }}
      pr-number: ${{ github.event.pull_request.number }}
      image-uri: ${{ needs.build-ephemeral-image.outputs.image-uri }}
