name: Deploy Ephemeral Environment

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize
      - labeled

permissions:
  contents: read
  id-token: write
  pull-requests: read

jobs:
  build-ephemeral-image:
    if:
      ${{ contains(github.event.pull_request.labels.*.name,
      'ephemeral-environment') }}
    uses: icanbwell/up-github-actions/.github/workflows/centralized-docker-publish.yml@main
    with:
      service-name: fhir-server
      tag: ${{ github.event.pull_request.head.sha }}
      ref: ${{ github.event.pull_request.head.sha }}
      env: dev
    secrets: inherit

  deploy-ephemeral-environment:
    needs: build-ephemeral-image
    uses: icanbwell/actions/.github/workflows/deploy-ephemeral-environment.yml@main
    secrets: inherit
    with:
      organization: ${{ github.event.organization.login }}
      repository: ${{ github.event.repository.name }}
      pr-number: ${{ github.event.pull_request.number }}
      image-uri:
        856965016623.dkr.ecr.us-east-1.amazonaws.com/fhir-server:${{
        github.event.pull_request.head.sha }}
