# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
    workflow_dispatch:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    build:
        runs-on: ubuntu-latest
        name: test (chunk ${{ matrix.chunk }})
        strategy:
          matrix:
            shard: [1, 2, 3, 4, 5, 6, 7, 8]
          fail-fast: false
        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js 16.18.1
              uses: actions/setup-node@v3
              with:
                  node-version: 16.18.1
            - run: | # retry since mongo memory server fails to download sometimes
                yarn install || yarn install
            - run: npm run build --if-present
            - name: jest
              run: |
                export NODE_OPTIONS="--max_old_space_size=8192"
                node --max_old_space_size=8192 --optimize_for_size --gc_interval=100 --always-compact ./node_modules/.bin/jest --no-watchman --silent --logHeapUsage --forceExit --shard=${{ matrix.shard }}/${{ strategy.job-total }}
              env:
                  NODE_OPTIONS: "--max_old_space_size=8192"
